import { SeedProductDef } from './catalog-data-part1';

export const CATALOG_PART_2: SeedProductDef[] = [
	// ── SPORTS & FITNESS (17 Products) ────────────────────────────────────────
	{
		name: 'Bowflex SelectTech 552 Adjustable Dumbbells',
		brand: 'Bowflex',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'strength-free-weights',
		description: 'Space-saving home gym dumbbells that replace 15 sets of weights with a turn of a dial, adjusting from 5 to 52.5 lbs in 2.5 lb increments.',
		variantName: 'Matte Black Red',
		weight: 47.6,
		sizes: [
			{ size: 'Pair (5-52.5 lbs each)', price: 429, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Weight Range', value: '5 to 52.5 lbs per dumbbell (2.3 to 23.8 kg)' },
			{ name: 'Adjustment Increments', value: '2.5 lb increments for the first 25 lbs' },
			{ name: 'Mechanism', value: 'Dual mechanical selection dials with interlocking catch' },
		],
		photoIds: [
			'1583454110551-21f2fa2afe61',
			'1534438327276-14e5300c3a48',
			'1574680096145-d05b474e2155',
			'1584735935682-2f2b69dff9d2',
			'1517838277536-f5f99be501cd',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Brock Lesnar-Smith', review: 'Replaces an entire dumbbell rack in our spare bedroom corner. The dial clicks into place securely with no plate rattle during presses.' },
			{ rating: 5, reviewerName: 'Samantha Briggs', review: 'Rubberized grip contours comfortably across the palm. Adjusting weights between drop sets takes literally three seconds.' },
			{ rating: 4, reviewerName: 'Mat Fraser-Vance', review: 'Durable composite molded plates protect wood floors from scuffing. A true home fitness staple.' },
		],
	},
	{
		name: 'Garmin Fenix 7 Pro Solar Multisport GPS Watch',
		brand: 'Garmin',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'Rugged GPS smart watch with Power Sapphire solar charging lens, built-in LED flashlight, multi-band GNSS satIQ, and endurance score analytics.',
		variantName: 'Titanium Slate Grey',
		weight: 0.073,
		sizes: [
			{ size: '47mm Standard Solar', price: 799, discount: 0, quantity: 20 },
			{ size: '51mm Sapphire Solar', price: 899, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Lens Material', value: 'Power Sapphire with Solar Harvesting Ring' },
			{ name: 'Battery Life', value: 'Up to 22 days in smartwatch mode with solar' },
			{ name: 'Flashlight', value: 'Built-in variable intensity LED strobe flashlight' },
		],
		photoIds: [
			'1523275335684-37898b6baf30',
			'1508685096489-7aacd43bd3b1',
			'1524805444758-089113d48a6d',
			'1522335789203-aabd1fc54bc9',
			'1533139502658-0198f920d8e8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Kilian Jornet-Cole', review: 'Topographical trail maps with hill score elevation profiles make navigating unfamiliar mountain ridgelines effortless.' },
			{ rating: 5, reviewerName: 'Courtney Dauwalter', review: 'The integrated white/red LED flashlight is surprisingly indispensable during early morning trailhead starts.' },
			{ rating: 4, reviewerName: 'Jim Walmsley', review: 'Solar charging ring genuinely extends battery life on multi-day ultramarathon backcountry efforts.' },
		],
	},
	{
		name: 'Specialized S-Works Tarmac SL8 Road Frameset',
		brand: 'Specialized',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'The fastest race bicycle in the world engineered with FACT 12r carbon, Speed Sniffer nose cone, and featherweight 685g frame geometry.',
		variantName: 'Gloss Carbon Flake Silver',
		weight: 6.6,
		sizes: [
			{ size: '52 cm', price: 5500, discount: 0, quantity: 4 },
			{ size: '54 cm', price: 5500, discount: 0, quantity: 6 },
			{ size: '56 cm', price: 5500, discount: 0, quantity: 5 },
		],
		specs: [
			{ name: 'Frame Material', value: 'S-Works FACT 12r Carbon, Rider-First Engineered' },
			{ name: 'Weight', value: '685g frame weight (Size 56)' },
			{ name: 'Cockpit', value: 'Roval Rapide integrated aero bar and stem' },
		],
		photoIds: [
			'1485965120184-e220f721d03e',
			'1532298229144-0ec0c57515c7',
			'1507035895480-2b3156c31fc8',
			'1511994298241-608e28f14fde',
			'1576435728678-68d0fbf94e91',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Remco Evenepoel', review: 'Stiffness under maximum sprint wattage transfers power instantly with zero bottom-bracket flex.' },
			{ rating: 5, reviewerName: 'Julian Alaphilippe', review: 'Featherlight on double-digit gradient climbs yet slices through headwind flats like a dedicated time-trial machine.' },
			{ rating: 4, reviewerName: 'Peter Sagan-Ross', review: 'Superb road dampening through the rear stays absorbs chip-seal tarmac chatter comfortably.' },
		],
	},
	{
		name: 'Manduka PRO 6mm High-Density Yoga Mat',
		brand: 'Manduka',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'yoga-recovery',
		description: 'The #1 yoga teacher-recommended mat featuring ultra-dense 6mm joint cushioning, closed-cell hygienic surface, and lifetime guarantee.',
		variantName: 'Black Sage',
		weight: 3.4,
		sizes: [
			{ size: 'Standard 71-inch', price: 138, discount: 0, quantity: 35 },
			{ size: 'Long 85-inch', price: 152, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Thickness', value: '6.0 mm High-Density PVC' },
			{ name: 'Surface', value: 'Closed-cell moisture barrier prevents sweat absorption' },
			{ name: 'Eco Certification', value: 'OEKO-TEX certified, emission-free manufacturing' },
		],
		photoIds: [
			'1518611012118-696072aa579a',
			'1544367567-0f2fcb009e0b',
			'1506126613408-eca07ce68773',
			'1592417817098-8f3d6910985b',
			'1575052814086-f385e2e2ad1b',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Adriene Mishler', review: 'The dense cushioning protects sensitive knees and wrists on hard studio floors without feeling spongy or unstable.' },
			{ rating: 5, reviewerName: 'Tara Stiles', review: 'Grip actually improves the more you practice. Salt scrub treatment unlocks immediate maximum traction.' },
			{ rating: 4, reviewerName: 'Rodney Yee', review: 'Heavier than lightweight travel mats, but this is a permanent foundation mat that will last 20+ years.' },
		],
	},
	{
		name: 'Concept2 RowErg Indoor Rowing Machine with PM5',
		brand: 'Concept2',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'strength-free-weights',
		description: 'The recognized standard for indoor rowing training worldwide engineered with flywheel air resistance, spiral damper, and backlit PM5 performance monitor.',
		variantName: 'Matte Black Powdercoat',
		weight: 26.0,
		sizes: [
			{ size: 'Standard 14-inch Seat Height', price: 990, discount: 0, quantity: 12 },
			{ size: 'Tall 20-inch Seat Height', price: 1100, discount: 0, quantity: 8 },
		],
		specs: [
			{ name: 'Resistance', value: 'Flywheel air resistance with 1-10 spiral damper' },
			{ name: 'Monitor', value: 'PM5 Performance Monitor with Bluetooth/ANT+ connectivity' },
			{ name: 'Storage', value: 'Separates easily into two segments for vertical storage' },
		],
		photoIds: [
			'1534438327276-14e5300c3a48',
			'1583454110551-21f2fa2afe61',
			'1574680096145-d05b474e2155',
			'1584735935682-2f2b69dff9d2',
			'1517838277536-f5f99be501cd',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Sir Steve Redgrave', review: 'Smooth, continuous water-like catch feel. The PM5 monitor syncs workout data with ErgData and Strava instantly.' },
			{ rating: 5, reviewerName: 'Camilla Brown', review: 'Engages 86% of muscles for a low-impact cardio session that spares the knees. Splits in half in seconds for closet storage.' },
			{ rating: 4, reviewerName: 'Matthew Pinsent', review: 'Bulletproof build quality. Replaced the chain oil once and it operates identically to day one.' },
		],
	},
	{
		name: 'Hydro Flask 32 oz Wide Mouth with Flex Straw Lid',
		brand: 'Hydro Flask',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'camping-shelters',
		description: 'TempShield double-wall vacuum insulated stainless steel water bottle keeping beverages ice cold for up to 24 hours or piping hot for 12 hours.',
		variantName: 'Pacific Blue',
		weight: 0.43,
		sizes: [
			{ size: '32 oz (946 ml)', price: 44, discount: 0, quantity: 60 },
			{ size: '40 oz (1182 ml)', price: 49, discount: 0, quantity: 45 },
		],
		specs: [
			{ name: 'Insulation', value: 'TempShield Double Wall Vacuum' },
			{ name: 'Steel Grade', value: 'Pro-grade 18/8 Stainless Steel' },
			{ name: 'Coating', value: 'Color Last powder coat, dishwasher safe' },
		],
		photoIds: [
			'1602143407151-7111542de6e8',
			'1523362628745-0c100150b504',
			'1544816155-12df9643f363',
			'1570831739427-440a049e88b8',
			'1546868871-7041f2a55e12',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Alex Honnold-Smith', review: 'Left inside a hot car in Arizona during mid-day and ice cubes were still rattling inside 8 hours later.' },
			{ rating: 5, reviewerName: 'Brooke Raboutou', review: 'The leakproof flex straw cap allows one-handed hydration while driving or climbing without tipping the bottle up.' },
			{ rating: 4, reviewerName: 'Tommy Caldwell', review: 'Powder coat provides secure grip even with sweaty hands or chalk.' },
		],
	},
	{
		name: 'Hoka Bondi 8 Maximum Cushion Running Shoes',
		brand: 'Hoka',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'The ultra-cushioned road runner featuring lighter, softer EVA foam, extended heel with billowed grooves, and ortholite hybrid sockliner.',
		variantName: 'Castlerock / Fiesta Red',
		weight: 0.307,
		sizes: [
			{ size: 'US 9.0 D', price: 165, discount: 0, quantity: 20 },
			{ size: 'US 10.0 D', price: 165, discount: 0, quantity: 35 },
			{ size: 'US 11.0 D', price: 165, discount: 0, quantity: 28 },
			{ size: 'US 12.0 D', price: 165, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Cushioning', value: 'Maximum plush EVA midsole foam' },
			{ name: 'Geometry', value: 'Early stage Meta-Rocker for smooth heel-to-toe transition' },
			{ name: 'Drop', value: '4 mm heel-to-toe offset' },
		],
		photoIds: [
			'1542291026-7eec264c27ff',
			'1595950653106-6c9ebd614d3a',
			'1560769629-975ec94e6a86',
			'1608256246200-53e635b5b65f',
			'1520639888713-7851133b1ed0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Desiree Linden', review: 'Absorbs joint impact on 20-mile Sunday long runs on hard asphalt roads. Legs feel significantly fresher the following morning.' },
			{ rating: 5, reviewerName: 'Meb Keflezighi', review: 'The wide base provides surprising stability despite the substantial stack height. Meta-Rocker rolls smoothly through toe-off.' },
			{ rating: 4, reviewerName: 'Shalane Flanagan', review: 'Plush heel collar and memory foam tongue lock the foot down without lace bite.' },
		],
	},
	{
		name: 'On Running Cloudtilt Ultra-Cushioned Walking Sneakers',
		brand: 'On',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'Precision-engineered lifestyle sneakers powered by computer-generated CloudTec Phase midsole technology for sequential weight transfer.',
		variantName: 'All Black',
		weight: 0.229,
		sizes: [
			{ size: 'US 8.5', price: 160, discount: 0, quantity: 18 },
			{ size: 'US 9.5', price: 160, discount: 0, quantity: 30 },
			{ size: 'US 10.5', price: 160, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Midsole Tech', value: 'CloudTec Phase with computer-modeled finite element analysis' },
			{ name: 'Upper', value: '100% recycled polyester mesh sock-fit construction' },
			{ name: 'Lacing', value: 'Speed-lacing system for pull-on convenience' },
		],
		photoIds: [
			'1549298916-b41d501d3772',
			'1560769629-975ec94e6a86',
			'1595950653106-6c9ebd614d3a',
			'1542291026-7eec264c27ff',
			'1608256246200-53e635b5b65f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Roger Federer-Smith', review: 'Featherlight sock-like fit that cushions every walking stride through airport terminals and urban city streets.' },
			{ rating: 5, reviewerName: 'Iga Swiatek', review: 'The sequential collapsing of the Cloud elements creates a uniquely smooth rolling sensation from heel to toe.' },
			{ rating: 4, reviewerName: 'Ben Shelton', review: 'Speed laces make slipping them on effortless without untying.' },
		],
	},
	{
		name: 'Wahoo KICKR v6 Smart Direct-Drive Bike Trainer',
		brand: 'Wahoo Fitness',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'Top-tier indoor smart trainer featuring built-in Wi-Fi connectivity, AXIS action feet for side-to-side natural sway, and +/- 1% power accuracy.',
		variantName: 'Matte Charcoal Steel',
		weight: 21.3,
		sizes: [
			{ size: 'Direct-Drive Unit with 11-Speed Cassette', price: 1299, discount: 0, quantity: 10 },
		],
		specs: [
			{ name: 'Power Accuracy', value: '+/- 1% with automatic continuous calibration' },
			{ name: 'Max Power / Grade', value: '2200 Watts / 20% simulated incline' },
			{ name: 'Connectivity', value: 'Direct Wi-Fi, Bluetooth Smart, ANT+ FE-C' },
		],
		photoIds: [
			'1485965120184-e220f721d03e',
			'1532298229144-0ec0c57515c7',
			'1507035895480-2b3156c31fc8',
			'1511994298241-608e28f14fde',
			'1576435728678-68d0fbf94e91',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Geraint Thomas', review: 'Wi-Fi connection eliminates Bluetooth packet dropouts in busy home networks during Zwift race sprints.' },
			{ rating: 5, reviewerName: 'Wout van Aert', review: 'AXIS feet provide 5 degrees of lateral sway that reduces saddle numbness on 3-hour indoor endurance rides.' },
			{ rating: 4, reviewerName: 'Tadej Pogacar-Smith', review: 'Virtually silent flywheel operation. All you hear is the bike chain spinning.' },
		],
	},
	{
		name: 'Theragun PRO Gen 5 Deep Tissue Percussive Massager',
		brand: 'Therabody',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'yoga-recovery',
		description: 'Commercial-grade percussive therapy device with patented 16mm amplitude, quiet proprietary brushless motor, and OLED visual routine screen.',
		variantName: 'Carbon Black',
		weight: 1.25,
		sizes: [
			{ size: 'PRO Gen 5 Device + 6 Attachments', price: 599, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Amplitude', value: '16 mm depth for deep muscle percussive penetration' },
			{ name: 'Force', value: 'Delivers up to 60 lbs of stall-free force' },
			{ name: 'Arm Articulation', value: '4 adjustable arm positions for complete body reach' },
		],
		photoIds: [
			'1583454110551-21f2fa2afe61',
			'1534438327276-14e5300c3a48',
			'1574680096145-d05b474e2155',
			'1584735935682-2f2b69dff9d2',
			'1517838277536-f5f99be501cd',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dr. Jason Wersland', review: '16mm amplitude reaches deep muscle bellies that vibration rollers cannot touch. Relieves hamstring stiffness post-squat.' },
			{ rating: 5, reviewerName: 'Cristiano Ronaldo-Smith', review: 'Rotating arm angle allows self-treating between the shoulder blades without awkward wrist twisting.' },
			{ rating: 4, reviewerName: 'LeBron James-Cole', review: 'OLED screen guides you through warm-up and sleep recovery routines with built-in force meter feedback.' },
		],
	},
	{
		name: 'Big Agnes Copper Spur HV UL2 Ultralight Backpacking Tent',
		brand: 'Big Agnes',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'camping-shelters',
		description: 'Award-winning 3-season ultralight freestanding backpacking tent with dual awning-style vestibules, DAC Featherlite aluminum poles, and proprietary double-ripstop nylon.',
		variantName: 'Olive Green / Orange',
		weight: 1.42,
		sizes: [
			{ size: '2-Person Ultralight', price: 549, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Trail Weight', value: '3 lbs 2 oz (1.42 kg)' },
			{ name: 'Floor Area', value: '29 sq ft + 18 sq ft total vestibule coverage' },
			{ name: 'Poles', value: 'DAC Featherlite NFL and NSL system' },
		],
		photoIds: [
			'1504280390367-361c6d9f38f4',
			'1510312305653-8ed496efae75',
			'1478131143081-80f7f84ca84d',
			'1523987355523-c7b5b0dd90a7',
			'1470246973918-29a93221c455',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Andrew Skurka', review: 'The high-volume hub pole architecture provides steep walls with genuine headroom to sit upright comfortably.' },
			{ rating: 5, reviewerName: 'Heather Anderson', review: 'With trekking poles you can prop the vestibule door open as an awning for cooking in rain without splash-in.' },
			{ rating: 4, reviewerName: 'Colin Fletcher-Vance', review: 'Silicone-treated ripstop holds strong against 40mph alpine gusts on exposed ridgelines.' },
		],
	},
	{
		name: 'YETI Tundra 45 Hard Wheeled Heavy-Duty Cooler',
		brand: 'YETI',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'camping-shelters',
		description: 'Virtually indestructible rotomolded cooler with PermaFrost pressure-injected polyurethane foam insulation and certified bear-resistant construction.',
		variantName: 'Desert Tan',
		weight: 10.4,
		sizes: [
			{ size: '45 Quart (Holds 28 Cans)', price: 325, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Construction', value: 'Rotomolded polyethylene unibody shell' },
			{ name: 'Insulation', value: 'Up to 3 inches of commercial-grade PermaFrost Foam' },
			{ name: 'Latches', value: 'T-Rex heavy-duty rubber lid latches with molded keeper slots' },
		],
		photoIds: [
			'1504280390367-361c6d9f38f4',
			'1510312305653-8ed496efae75',
			'1478131143081-80f7f84ca84d',
			'1523987355523-c7b5b0dd90a7',
			'1470246973918-29a93221c455',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Cody Lundin', review: 'Held block ice through a 5-day desert rafting trip in 95°F heat. Cold drinks and fresh food all week.' },
			{ rating: 5, reviewerName: 'Bear Grylls-Smith', review: 'DoubleHaul handles and tie-down slots anchor securely in truck beds over washboard dirt roads.' },
			{ rating: 4, reviewerName: 'Les Stroud', review: 'Heavy empty weight, but the thermal retention and indestructible shell are completely unmatched.' },
		],
	},
	{
		name: 'Osprey Atmos AG 65 Anti-Gravity Backpack',
		brand: 'Osprey',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'camping-shelters',
		description: 'Expedition backpacking pack featuring continuous AntiGravity suspended 3D mesh suspension backpanel that wraps your body in seamless comfort.',
		variantName: 'Venturi Blue',
		weight: 2.18,
		sizes: [
			{ size: 'S/M (65L)', price: 340, discount: 0, quantity: 16 },
			{ size: 'L/XL (68L)', price: 340, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Suspension', value: 'Anti-Gravity (AG) continuous backpanel-to-hipbelt mesh' },
			{ name: 'Capacity', value: '65 Liters with floating removable lid' },
			{ name: 'Raincover', value: 'Integrated PFC/PFAS-free DWR raincover included' },
		],
		photoIds: [
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
			'1577733966973-d680bffd2e80',
			'1581605405669-fcdf81165afa',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Jennifer Pharr Davis', review: 'Carried 42 lbs across the 100-Mile Wilderness with zero pressure points or sore hips. Mesh back allows great airflow.' },
			{ rating: 5, reviewerName: 'Scott Jurek', review: 'The Stow-on-the-Go trekking pole attachment lets you stash poles without taking off the pack.' },
			{ rating: 4, reviewerName: 'Harvey Manning', review: 'Sleeping bag compartment with removable divider keeps damp camp gear separated from dry clothes.' },
		],
	},
	{
		name: 'Brooks Ghost 15 Neutral Road Running Shoes',
		brand: 'Brooks',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'The reliable daily trainer trusted by runners everywhere with refined DNA LOFT v2 cushioning, engineered air mesh upper, and smooth segmented crash pad.',
		variantName: 'Black / Oyster / Orange',
		weight: 0.286,
		sizes: [
			{ size: 'US 9.0 D', price: 140, discount: 0, quantity: 24 },
			{ size: 'US 10.0 D', price: 140, discount: 0, quantity: 36 },
			{ size: 'US 11.0 D', price: 140, discount: 0, quantity: 30 },
		],
		specs: [
			{ name: 'Midsole', value: 'DNA LOFT v2 nitrogen-infused EVA compound' },
			{ name: 'Support Level', value: 'Neutral with Segmented Crash Pad' },
			{ name: 'Drop', value: '12 mm heel drop' },
		],
		photoIds: [
			'1542291026-7eec264c27ff',
			'1595950653106-6c9ebd614d3a',
			'1560769629-975ec94e6a86',
			'1608256246200-53e635b5b65f',
			'1520639888713-7851133b1ed0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Ryan Hall-Smith', review: 'The definition of a dependable daily workhorse shoe. Put 500 miles on my previous pair with zero outsole peeling.' },
			{ rating: 5, reviewerName: 'Sara Hall-Vance', review: 'DNA LOFT v2 is softer and lighter than previous iterations without feeling mushy under the ball of your foot.' },
			{ rating: 4, reviewerName: 'Dean Karnazes', review: 'Breathable toe box mesh prevents blister hot-spots during humid summer morning workouts.' },
		],
	},
	{
		name: 'Black Diamond Trail Pro Shock Trekking Poles',
		brand: 'Black Diamond',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'camping-shelters',
		description: 'Four-season aluminum trekking poles with SmashLock quick-release technology, Control Shock absorption, and dual FlickLock Pro metal cam adjustments.',
		variantName: 'Titanium Anodized Red',
		weight: 0.59,
		sizes: [
			{ size: 'Pair (100–140cm adjustable)', price: 169, discount: 0, quantity: 22 },
		],
		specs: [
			{ name: 'Shaft Material', value: '7075 Aluminum 3-Section Shaft' },
			{ name: 'Locking System', value: 'Dual FlickLock Pro forged aluminum levers + SmashLock' },
			{ name: 'Shock Mechanism', value: 'Centering Control Shock elastomer dampening' },
		],
		photoIds: [
			'1504280390367-361c6d9f38f4',
			'1510312305653-8ed496efae75',
			'1478131143081-80f7f84ca84d',
			'1523987355523-c7b5b0dd90a7',
			'1470246973918-29a93221c455',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Conrad Anker', review: 'SmashLock lower mechanism collapses with a single pull when transitioning to scrambling sections.' },
			{ rating: 5, reviewerName: 'Jimmy Chin', review: 'FlickLock Pro aluminum cams never slip even in freezing wet sub-zero conditions.' },
			{ rating: 4, reviewerName: 'Ed Viesturs', review: 'The elastomer shock dampener absorbs wrist vibration on steep rocky descents.' },
		],
	},
	{
		name: 'Salomon Speedcross 6 Gore-Tex Trail Running Shoes',
		brand: 'Salomon',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'cycling-road-bikes',
		description: 'Fierce trail shoe designed for aggressive grip in muddy, loose terrain with Gore-Tex waterproof membrane, Sensifit cradle, and Quicklace system.',
		variantName: 'Black / Phantom',
		weight: 0.328,
		sizes: [
			{ size: 'US 9.0', price: 170, discount: 0, quantity: 20 },
			{ size: 'US 10.0', price: 170, discount: 0, quantity: 30 },
			{ size: 'US 11.0', price: 170, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Lug Pattern', value: 'Deep chevron Mud Contagrip 5mm lugs' },
			{ name: 'Membrane', value: 'Gore-Tex waterproof/breathable bootie' },
			{ name: 'Lacing', value: 'One-pull Quicklace with lace garage pocket' },
		],
		photoIds: [
			'1542291026-7eec264c27ff',
			'1595950653106-6c9ebd614d3a',
			'1560769629-975ec94e6a86',
			'1608256246200-53e635b5b65f',
			'1520639888713-7851133b1ed0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Francois D’Haene', review: 'Bites into slick mud and loose wet leaves like track spikes. Gore-Tex keeps feet dry through bog crossings.' },
			{ rating: 5, reviewerName: 'Courtney Dauwalter-Smith', review: 'Sensifit upper locks down around the midfoot with zero heel slippage on technical switchbacks.' },
			{ rating: 4, reviewerName: 'Anton Krupicka', review: 'Quicklace system never loosens during wet downhills. Mud sheds rapidly from the chevron lugs.' },
		],
	},
	{
		name: 'Rogue Fitness Echo Olympic Bumper Plate Set',
		brand: 'Rogue Fitness',
		categoryUrl: 'sports-fitness',
		subCategoryUrl: 'strength-free-weights',
		description: 'Competition-diameter 450mm virgin rubber bumper plates with stainless steel inserts, dead bounce, and consistent shore A durometer hardness.',
		variantName: 'All Black with White Lettering',
		weight: 72.5,
		sizes: [
			{ size: '160 lb Set (Pair of 45, 25, 10 lb)', price: 395, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Plate Diameter', value: '450 mm IWF standard outer diameter' },
			{ name: 'Collar Opening', value: '50.4 mm precision stainless steel insert' },
			{ name: 'Durometer', value: '88 Shore A for low, predictable dead bounce' },
		],
		photoIds: [
			'1583454110551-21f2fa2afe61',
			'1534438327276-14e5300c3a48',
			'1574680096145-d05b474e2155',
			'1584735935682-2f2b69dff9d2',
			'1517838277536-f5f99be501cd',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Rich Froning', review: 'Dead bounce means dropping from overhead snatch lockouts stays in your lifting lane without wild rebounding.' },
			{ rating: 5, reviewerName: 'Tia-Clair Toomey', review: 'Virgin rubber has minimal odor right out of the packaging. Stainless steel center hubs slide on barbells smoothly.' },
			{ rating: 4, reviewerName: 'Dan Bailey', review: 'Tight tolerance on collar fit. Withstands daily gym abuse year after year.' },
		],
	},

	// ── BEAUTY & PERSONAL CARE (17 Products) ──────────────────────────────────
	{
		name: 'SkinCeuticals C E Ferulic Antioxidant Serum',
		brand: 'SkinCeuticals',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'facial-serums',
		description: 'The gold standard dermatological daytime vitamin C serum featuring synergistic 15% pure L-ascorbic acid, 1% alpha tocopherol, and 0.5% ferulic acid.',
		variantName: 'Amber Dropper Bottle',
		weight: 0.12,
		sizes: [
			{ size: '30 ml (1.0 fl oz)', price: 182, discount: 0, quantity: 40 },
		],
		specs: [
			{ name: 'Actives', value: '15% L-Ascorbic Acid, 1% Alpha Tocopherol, 0.5% Ferulic Acid' },
			{ name: 'pH Range', value: 'Optimized 2.0 to 3.5 for deep cutaneous absorption' },
			{ name: 'Protection', value: '8x environmental antioxidant photoprotection' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1556228720-195a672e8a03',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dr. Whitney Bowe', review: 'The patented concentration ratio provides measurable brightening and protects against UV and pollution free-radical damage.' },
			{ rating: 5, reviewerName: 'Caroline Hirons', review: 'Noticeable reduction in post-inflammatory hyperpigmentation and fine expression lines within 6 weeks of daily morning use.' },
			{ rating: 4, reviewerName: 'Charlotte Tilbury', review: 'Distinct metallic scent fades rapidly once absorbed. Layer under sunscreen for ideal daytime defense.' },
		],
	},
	{
		name: 'Le Labo Santal 33 Eau de Parfum',
		brand: 'Le Labo',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'artisanal-fragrances',
		description: 'Cult fragrance icon evoking smoky desert spirit with Australian sandalwood, cedarwood, cardamom, iris, violet, and rich leather accords.',
		variantName: 'Hand-Labeled Glass Flacon',
		weight: 0.28,
		sizes: [
			{ size: '50 ml (1.7 fl oz)', price: 230, discount: 0, quantity: 24 },
			{ size: '100 ml (3.4 fl oz)', price: 320, discount: 0, quantity: 30 },
		],
		specs: [
			{ name: 'Fragrance Family', value: 'Woody Smoky Leather' },
			{ name: 'Key Notes', value: 'Cardamom, Iris, Violet, Ambrox, Cedarwood, Sandalwood' },
			{ name: 'Concentration', value: 'Eau de Parfum, hand-blended formula' },
		],
		photoIds: [
			'1547887537-6158d64c35b3',
			'1592945403244-b3fbafd7f539',
			'1523293182086-7651a899d37f',
			'1594035910387-fea47794261f',
			'1588405748880-12d1d2a59f75',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Fabrice Penot', review: 'Incredible longevity on clothing and skin that projects intoxicating sandalwood and cardamom for over 12 hours.' },
			{ rating: 5, reviewerName: 'Sienna Miller', review: 'Unisex signature scent that draws compliments wherever you go. The smoky cedar drydown is hypnotic.' },
			{ rating: 4, reviewerName: 'Edouard Roschi', review: 'Distinctive and commanding fragrance. Two spritzes are more than enough.' },
		],
	},
	{
		name: 'Dyson Supersonic Nural Intelligent Hair Dryer',
		brand: 'Dyson',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'skincare-tools',
		description: 'Next-generation hair dryer equipped with Nural network sensors that automatically reduce heat as it approaches the scalp to preserve moisture barrier.',
		variantName: 'Vinca Blue & Topaz',
		weight: 0.68,
		sizes: [
			{ size: 'Complete Stylist Kit + 5 Attachments', price: 499, discount: 0, quantity: 22 },
		],
		specs: [
			{ name: 'Sensor Tech', value: 'Time-of-flight sensor scales heat to maintain 131°F at scalp' },
			{ name: 'Motor', value: 'V9 digital motor spinning at up to 110,000 RPM' },
			{ name: 'Attachments', value: 'Wave+Curl diffuser, gentle air tip, styling concentrator, flyaway smoother' },
		],
		photoIds: [
			'1522337360788-8b13dee7a37e',
			'1527799820374-dcf8d9d4a388',
			'1560750588-73207b1ef5b8',
			'1598440947619-2c35fc9aa908',
			'1608248597359-0010996191b7',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Jen Atkin', review: 'The scalp protect sensor changes the capsule light color from red to yellow to cool blue as you bring it closer. Never burns.' },
			{ rating: 5, reviewerName: 'Guido Palau', review: 'Dries thick wavy hair in under 7 minutes with zero frizz. Flyaway attachment finishes with glassy salon shine.' },
			{ rating: 4, reviewerName: 'Chris Appleton', review: 'Balanced weight distribution with motor in handle prevents forearm strain during precision blowouts.' },
		],
	},
	{
		name: 'Aesop Resurrection Aromatique Hand Balm',
		brand: 'Aesop',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'body-scalp-care',
		description: 'Replenishing botanical moisturizer with mandarin rind, rosemary leaf, and cedarwood atlas to hydrate hands and cuticles without greasy residue.',
		variantName: 'Amber Apothecary Tube',
		weight: 0.075,
		sizes: [
			{ size: '75 ml Tube', price: 35, discount: 0, quantity: 50 },
			{ size: '500 ml Pump Bottle', price: 105, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Aroma', value: 'Citrus, Woody, Herbaceous' },
			{ name: 'Texture', value: 'Medium-weight greaseless cream' },
			{ name: 'Key Botanicals', value: 'Mandarin Rind, Rosemary Leaf, Cedarwood Atlas' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1556228720-195a672e8a03',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dennis Paphitis', review: 'Instantly absorbs into dry winter skin. The crisp herbal rosemary and sweet mandarin scent is energizing.' },
			{ rating: 5, reviewerName: 'Kelly Wearstler', review: 'The apothecary amber tube looks elegant on bathroom consoles and desk setups. Non-greasy enough to type immediately.' },
			{ rating: 4, reviewerName: 'Rosie Huntington-Whiteley', review: 'Softens stubborn cuticle peeling within two applications. A true luxury self-care essential.' },
		],
	},
	{
		name: 'Maison Margiela Replica Jazz Club Eau de Toilette',
		brand: 'Maison Margiela',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'artisanal-fragrances',
		description: 'Evocative olfactory memory of a Brooklyn jazz club with cocktails, tobacco leaf, pink pepper, rum absolute, and vanilla bean notes.',
		variantName: 'Apothecary Label Flacon',
		weight: 0.29,
		sizes: [
			{ size: '30 ml (1.0 fl oz)', price: 85, discount: 0, quantity: 20 },
			{ size: '100 ml (3.4 fl oz)', price: 160, discount: 0, quantity: 28 },
		],
		specs: [
			{ name: 'Fragrance Profile', value: 'Warm & Spicy Boozy Woody' },
			{ name: 'Top Notes', value: 'Pink Pepper, Neroli, Lemon' },
			{ name: 'Base Notes', value: 'Tobacco Leaf, Vanilla Bean, Styrax' },
		],
		photoIds: [
			'1547887537-6158d64c35b3',
			'1592945403244-b3fbafd7f539',
			'1523293182086-7651a899d37f',
			'1594035910387-fea47794261f',
			'1588405748880-12d1d2a59f75',
		],
		reviews: [
			{ rating: 5, reviewerName: 'John Galliano-Cole', review: 'Captures the ambiance of dim candlelight, leather banquettes, and aged bourbon in a crystal tumbler.' },
			{ rating: 5, reviewerName: 'Alexa Chung', review: 'Warm boozy vanilla and spiced tobacco aroma that feels cozy on cold rainy autumn evenings.' },
			{ rating: 4, reviewerName: 'Nick Cave-Smith', review: 'Projects gracefully without overpowering intimate dinner conversations. 8-hour longevity on wool jackets.' },
		],
	},
	{
		name: 'Sunday Riley Good Genes All-In-One Lactic Acid Treatment',
		brand: 'Sunday Riley',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'facial-serums',
		description: 'Purified grade lactic acid treatment that clarifies, exfoliates, and brightens dull skin while instantly plumping the look of fine lines.',
		variantName: 'Glass Pump Dispenser',
		weight: 0.16,
		sizes: [
			{ size: '30 ml (1.0 fl oz)', price: 85, discount: 0, quantity: 30 },
			{ size: '50 ml (1.7 fl oz)', price: 122, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Exfoliant', value: 'High-potency purified Lactic Acid (AHA)' },
			{ name: 'Brightening Botanicals', value: 'Licorice, Lemongrass, Arnica, Prickly Pear' },
			{ name: 'Texture', value: 'Lightweight creamy hydrating serum' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1556228720-195a672e8a03',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Sunday Riley-Smith', review: 'Dead skin cells dissolve gently overnight revealing radiant glowing clarity by morning without redness or peeling.' },
			{ rating: 5, reviewerName: 'Dr. Barbara Sturm', review: 'Lactic acid has larger molecular size than glycolic, making it significantly gentler for sensitive skin types.' },
			{ rating: 4, reviewerName: 'Jessica Alba-Ross', review: 'Plumps skin texture before applying makeup. Smooths uneven pore texture effectively.' },
		],
	},
	{
		name: 'Diptyque Baies Scented Luxury Candle',
		brand: 'Diptyque',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'artisanal-fragrances',
		description: 'The Parisian benchmark home scent blending the tangy freshness of freshly-picked blackcurrant berries with lively flowering rose accents.',
		variantName: 'Classic Clear Glass Vessel',
		weight: 0.58,
		sizes: [
			{ size: '190g Classic (60-Hour Burn)', price: 78, discount: 0, quantity: 35 },
		],
		specs: [
			{ name: 'Wax Blend', value: 'Proprietary vegetable and paraffin wax formulation' },
			{ name: 'Wick', value: 'Pure braided lead-free cotton wick' },
			{ name: 'Origin', value: 'Handmade in Paris, France' },
		],
		photoIds: [
			'1547887537-6158d64c35b3',
			'1523293182086-7651a899d37f',
			'1592945403244-b3fbafd7f539',
			'1594035910387-fea47794261f',
			'1588405748880-12d1d2a59f75',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Desmond Knox-Leet', review: 'Fills the entire apartment with the scent of a summer rose garden and wild blackcurrant bushes within 20 minutes.' },
			{ rating: 5, reviewerName: 'Christiane Montadre', review: 'Burns cleanly with zero black soot when the wick is trimmed. The oval label typography is timeless.' },
			{ rating: 4, reviewerName: 'Ines de la Fressange', review: 'The empty glass makes a charming desk container for pens or makeup brushes once melted.' },
		],
	},
	{
		name: 'Augustinus Bader The Rich Cream with TFC8',
		brand: 'Augustinus Bader',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'facial-serums',
		description: 'Award-winning cellular renewal moisturizer backed by 30 years of stem cell research with Trigger Factor Complex TFC8, argan oil, and evening primrose.',
		variantName: 'Cobalt Glass Vessel with Copper Cap',
		weight: 0.22,
		sizes: [
			{ size: '30 ml (1.0 fl oz)', price: 185, discount: 0, quantity: 20 },
			{ size: '50 ml (1.7 fl oz)', price: 290, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Patented Technology', value: 'TFC8 (Trigger Factor Complex) peptide blend' },
			{ name: 'Lipids', value: 'Argan, Avocado, and Evening Primrose botanical oils' },
			{ name: 'Skin Target', value: 'Dry to very dry skin, barrier repair, deep elasticity' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1571781926291-c477ebfd024b',
			'1556228720-195a672e8a03',
			'1598440947619-2c35fc9aa908',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Professor Augustinus Bader', review: 'The proprietary TFC8 complex guides key nutrients to skin cells to support your body’s natural repair biology.' },
			{ rating: 5, reviewerName: 'Victoria Beckham', review: 'Transformed dry winter flaky skin into a supple, dewy canvas. Replaces separate eye creams and daytime serums.' },
			{ rating: 4, reviewerName: 'Hailey Bieber-Smith', review: 'Rich velvety texture melts on skin contact without leaving a greasy sheen. Flawless makeup base.' },
		],
	},
	{
		name: 'Byredo Gypsy Water Eau de Parfum',
		brand: 'Byredo',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'artisanal-fragrances',
		description: 'Ode to the beauty of Romany culture featuring bergamot, lemon, pepper, juniper berries, pine needles, incense, orris, and golden amber.',
		variantName: 'Minimalist Magnetic Cap Bottle',
		weight: 0.27,
		sizes: [
			{ size: '50 ml (1.7 fl oz)', price: 205, discount: 0, quantity: 18 },
			{ size: '100 ml (3.4 fl oz)', price: 290, discount: 0, quantity: 24 },
		],
		specs: [
			{ name: 'Top Notes', value: 'Bergamot, Lemon, Pepper, Juniper Berries' },
			{ name: 'Heart Notes', value: 'Incense, Pine Needles, Orris' },
			{ name: 'Base Notes', value: 'Amber, Vanilla, Sandalwood' },
		],
		photoIds: [
			'1547887537-6158d64c35b3',
			'1592945403244-b3fbafd7f539',
			'1523293182086-7651a899d37f',
			'1594035910387-fea47794261f',
			'1588405748880-12d1d2a59f75',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Ben Gorham', review: 'Fresh pine forest needles mixed with sweet lemon and soft smoky vanilla amber. Intimate, ethereal scent trail.' },
			{ rating: 5, reviewerName: 'Kate Bosworth', review: 'Effortless daytime fragrance that feels clean, mysterious, and uplifting all at once.' },
			{ rating: 4, reviewerName: 'Cillian Murphy-Vance', review: 'The juniper and citrus opening is sparkling and transitions gracefully into woody incense.' },
		],
	},
	{
		name: 'Braun Series 9 PRO+ Electric Shaver with SmartCare Center',
		brand: 'Braun',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'skincare-tools',
		description: 'The world’s most efficient electric shaver with 5 synchronized shaving elements, ProLift blade, sonic technology, and 6-in-1 alcohol cleaning station.',
		variantName: 'Matte Chrome Silver',
		weight: 0.98,
		sizes: [
			{ size: 'Complete Pro+ System & SmartCare Dock', price: 379, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Sonic Technology', value: '10,000 micro-vibrations per minute capture more hair' },
			{ name: 'Blade System', value: 'Titanium-coated ProLift trimmer cuts flat-lying hairs' },
			{ name: 'Cleaning Dock', value: '6-in-1 SmartCare cleans, lubricates, dries, and charges' },
		],
		photoIds: [
			'1522337360788-8b13dee7a37e',
			'1527799820374-dcf8d9d4a388',
			'1560750588-73207b1ef5b8',
			'1598440947619-2c35fc9aa908',
			'1608248597359-0010996191b7',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dieter Rams-Smith', review: 'Provides manual blade closeness without a single drop of razor burn or ingrown hair irritation across neck contours.' },
			{ rating: 5, reviewerName: 'George Clooney-Ross', review: 'The SmartCare cleaning dock leaves the shaver feeling brand new and citrus-fresh every morning.' },
			{ rating: 4, reviewerName: 'Daniel Craig-Vance', review: 'Handles a tough 3-day weekend beard in single passes without tugging or pulling.' },
		],
	},
	{
		name: 'Dr. Dennis Gross SpectraLite FaceWare Pro LED Mask',
		brand: 'Dr. Dennis Gross',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'skincare-tools',
		description: 'FDA-cleared medical-grade full-face light therapy mask combining 100 red LED lights to boost collagen and 62 blue lights to clear acne in 3-minute treatments.',
		variantName: 'Pearl White Gold Accents',
		weight: 0.62,
		sizes: [
			{ size: 'FaceWare Pro Device Unit', price: 455, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'LED Configuration', value: '100 Red (630nm/880nm) + 62 Blue (415nm) LEDs' },
			{ name: 'Treatment Time', value: 'Automated 3-minute auto-shutoff daily program' },
			{ name: 'FDA Status', value: 'FDA 510(k) Cleared Class II Medical Device' },
		],
		photoIds: [
			'1522337360788-8b13dee7a37e',
			'1560750588-73207b1ef5b8',
			'1527799820374-dcf8d9d4a388',
			'1598440947619-2c35fc9aa908',
			'1608248597359-0010996191b7',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dr. Dennis Gross', review: 'Dual red and blue spectrums stimulate fibroblast collagen synthesis while destroying acne bacteria simultaneously.' },
			{ rating: 5, reviewerName: 'Gwyneth Paltrow-Smith', review: 'Consistent 3-minute daily sessions visibly smoothed forehead lines and calmed rosacea redness within 4 weeks.' },
			{ rating: 4, reviewerName: 'Miranda Kerr', review: 'Hands-free design with adjustable silicone strap allows multitasking while reading or answering emails.' },
		],
	},
	{
		name: 'Kiehl’s Ultra Facial Cream with Glacial Glycoprotein',
		brand: 'Kiehl’s',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'facial-serums',
		description: 'America’s #1 face cream providing 24-hour non-greasy barrier hydration with Antarctic glacial glycoprotein and olive-derived squalane.',
		variantName: 'White Recycled Jar',
		weight: 0.15,
		sizes: [
			{ size: '50 ml (1.7 fl oz)', price: 38, discount: 0, quantity: 45 },
			{ size: '125 ml (4.2 fl oz)', price: 68, discount: 0, quantity: 30 },
		],
		specs: [
			{ name: 'Hero Ingredients', value: 'Glacial Glycoprotein, Olive-derived Squalane' },
			{ name: 'Texture', value: 'Lightweight, ultra-absorbent whipped cream' },
			{ name: 'Barrier Testing', value: 'Clinically tested in extreme winter environments' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1556228720-195a672e8a03',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'John Kiehl-Smith', review: 'Leaves dry skin feeling balanced and supple all day without greasiness or pore clogging.' },
			{ rating: 5, reviewerName: 'Emilia Clarke', review: 'Saved my skin during sub-zero filming outdoors. Keeps the lipid barrier sealed against moisture loss.' },
			{ rating: 4, reviewerName: 'Paul Rudd', review: 'Gentle, unscented, and layers effortlessly under any mineral sunscreen without pilling.' },
		],
	},
	{
		name: 'Jo Malone London Wood Sage & Sea Salt Cologne',
		brand: 'Jo Malone London',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'artisanal-fragrances',
		description: 'Windblown British coast fragrance mingling mineral salt spray with woody earthy sage, red algae, and ambrette seed notes.',
		variantName: 'Fluted Crystal Bottle',
		weight: 0.28,
		sizes: [
			{ size: '30 ml (1.0 fl oz)', price: 82, discount: 0, quantity: 25 },
			{ size: '100 ml (3.4 fl oz)', price: 165, discount: 0, quantity: 28 },
		],
		specs: [
			{ name: 'Top Note', value: 'Ambrette Seeds, Sea Salt spray' },
			{ name: 'Heart Note', value: 'Crunchy Mineral Salt, Red Algae' },
			{ name: 'Base Note', value: 'Sage, Earthy Woody Base' },
		],
		photoIds: [
			'1547887537-6158d64c35b3',
			'1592945403244-b3fbafd7f539',
			'1523293182086-7651a899d37f',
			'1594035910387-fea47794261f',
			'1588405748880-12d1d2a59f75',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Joanne Malone', review: 'Smells exactly like sea spray on rugged clifftops. Fresh, sophisticated, and completely non-cloying.' },
			{ rating: 5, reviewerName: 'Poppy Delevingne', review: 'Pairs beautifully layered over warmer vanilla or amber perfumes. The sage brings grounding balance.' },
			{ rating: 4, reviewerName: 'David Gandy', review: 'Subtle sillage makes it the perfect signature scent for professional indoor office settings.' },
		],
	},
	{
		name: 'Mason Pearson Handy Bristle & Nylon Hairbrush',
		brand: 'Mason Pearson',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'skincare-tools',
		description: 'Handmade London heirloom hairbrush featuring ethical natural boar bristles and nylon spikes set into a patented pneumatic rubber cushion.',
		variantName: 'Dark Ruby Red Handle',
		weight: 0.14,
		sizes: [
			{ size: 'Handy BN3 Size', price: 275, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Bristles', value: 'Natural pure boar bristle & flexible nylon tufts' },
			{ name: 'Cushion', value: 'Patented hand-pressed pneumatic rubber pad' },
			{ name: 'Handle', value: 'Hand-polished cellulose acetate acrylic' },
		],
		photoIds: [
			'1522337360788-8b13dee7a37e',
			'1527799820374-dcf8d9d4a388',
			'1560750588-73207b1ef5b8',
			'1598440947619-2c35fc9aa908',
			'1608248597359-0010996191b7',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Vidal Sassoon-Smith', review: 'Distributes natural sebum oils from roots to dry ends for unmatched glossy shine and healthy scalp circulation.' },
			{ rating: 5, reviewerName: 'Rachel Zoe', review: 'An heirloom that lasts for decades. The nylon tips detangle knotty hair without pulling or hair breakage.' },
			{ rating: 4, reviewerName: 'Kate Moss-Vance', review: 'Handcrafted in London with Victorian pneumatic cushion design that massages the scalp gently.' },
		],
	},
	{
		name: 'Malin+Goetz Eucalyptus Natural Deodorant',
		brand: 'Malin+Goetz',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'body-scalp-care',
		description: 'Aluminum-free and baking soda-free natural deodorant stick formulated with natural eucalyptus extract and odor-neutralizing citronellyl.',
		variantName: 'Clean Twist Stick',
		weight: 0.073,
		sizes: [
			{ size: '2.6 oz (73 g)', price: 24, discount: 0, quantity: 50 },
		],
		specs: [
			{ name: 'Formula', value: 'Clean aluminum, alcohol, and baking soda free' },
			{ name: 'Botanicals', value: 'Natural Eucalyptus Extract & Citronellyl' },
			{ name: 'Residue', value: 'Clear glide formula leaves zero white pit stains on shirts' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1556228720-195a672e8a03',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Matthew Malin', review: 'Glides on completely clear without stinging or staining white undershirts. Eucalyptus aroma is crisp and clean.' },
			{ rating: 5, reviewerName: 'Andrew Goetz', review: 'Contains no baking soda, so there is zero red irritation for sensitive skin. Neutralizes odors through long workouts.' },
			{ rating: 4, reviewerName: 'Nate Berkus', review: 'One stick lasts 4 to 5 months of daily use. The best natural deodorant on the market.' },
		],
	},
	{
		name: 'Moroccanoil Treatment Original Argan Hair Oil',
		brand: 'Moroccanoil',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'body-scalp-care',
		description: 'The pioneering argan oil treatment infused with antioxidant-rich argan oil and shine-boosting vitamins for conditioning, styling, and finishing.',
		variantName: 'Amber Glass Bottle with Pump',
		weight: 0.24,
		sizes: [
			{ size: '100 ml (3.4 fl oz)', price: 48, discount: 0, quantity: 45 },
		],
		specs: [
			{ name: 'Core Ingredient', value: '100% Pure Argania Spinosa Kernel Oil' },
			{ name: 'Benefits', value: 'Detangles, speeds up blow-dry time, boosts shine by 118%' },
			{ name: 'Fragrance', value: 'Signature Mediterranean amber, floral, and musk notes' },
		],
		photoIds: [
			'1608248597359-0010996191b7',
			'1556228720-195a672e8a03',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1522337360788-8b13dee7a37e',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Carmen Tal', review: 'Two pumps worked into damp mid-lengths and ends eliminates frizz and speeds up blow drying significantly.' },
			{ rating: 5, reviewerName: 'Jennifer Lopez-Smith', review: 'Never weighs fine hair down. Leaves locks silky, luminous, and smelling like a five-star Mediterranean resort.' },
			{ rating: 4, reviewerName: 'Kim Kardashian-Vance', review: 'Tames humidity flyaways instantly with just a drop smoothed over dry styled hair.' },
		],
	},
	{
		name: 'Oribe Gold Lust Repair and Restore Shampoo',
		brand: 'Oribe',
		categoryUrl: 'beauty-personal-care',
		subCategoryUrl: 'body-scalp-care',
		description: 'Rejuvenating cleanser formulated with healing oils, cypress, argan, and maracuja to reinforce dry and distressed hair fibers.',
		variantName: 'Architectural Amber Bottle',
		weight: 0.32,
		sizes: [
			{ size: '250 ml (8.5 fl oz)', price: 53, discount: 0, quantity: 38 },
			{ size: '1000 ml Liter Refill', price: 156, discount: 5, quantity: 18 },
		],
		specs: [
			{ name: 'Key Actives', value: 'Bio-Restorative Complex (Plant Collagen, Caffeine, Biotin, Niacinamide)' },
			{ name: 'Botanical Oils', value: 'Mediterranean Cypress, Argan Oil, and Maracuja Oil' },
			{ name: 'Safety', value: 'Color and keratin treatment safe, sulfate and paraben free' },
		],
		photoIds: [
			'1522337360788-8b13dee7a37e',
			'1608248597359-0010996191b7',
			'1571781926291-c477ebfd024b',
			'1598440947619-2c35fc9aa908',
			'1556228720-195a672e8a03',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Daniel Kaner', review: 'Restores softness and shine after just one wash. The Cote d Azur signature scent smells incredible all day long.' },
			{ rating: 5, reviewerName: 'Oribe Canales-Smith', review: 'Lathers rich and creamy despite being sulfate-free. Leaves treated hair silky and noticeably stronger.' },
			{ rating: 4, reviewerName: 'Mindy Kaling-Jones', review: 'A little goes a long way. The bottle looks elegant on the shower ledge and the formula genuinely repairs distressed ends.' },
		],
	},

	// ── WATCHES & ACCESSORIES (16 Products) ───────────────────────────────────
	{
		name: 'Seiko Prospex Speedtimer Solar Chronograph',
		brand: 'Seiko',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'automatic-chronographs',
		description: 'Japanese racing chronograph powered by light energy with Caliber V192, sandblasted panda dial, sapphire crystal, and 6-month power reserve.',
		variantName: 'Panda White Dial',
		weight: 0.161,
		sizes: [
			{ size: '39mm Stainless Steel', price: 675, discount: 5, quantity: 24 },
		],
		specs: [
			{ name: 'Movement', value: 'Seiko Solar Caliber V192 (powered by any light)' },
			{ name: 'Case & Crystal', value: '39mm Stainless Steel with Curved Anti-Reflective Sapphire' },
			{ name: 'Water Resistance', value: '10 bar / 100 meters (330 feet)' },
		],
		photoIds: [
			'1524805444758-089113d48a6d',
			'1522335789203-aabd1fc54bc9',
			'1523275335684-37898b6baf30',
			'1508685096489-7aacd43bd3b1',
			'1533139502658-0198f920d8e8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Kintaro Hattori-Smith', review: 'The 39mm case proportions sit balanced on the wrist. Solar quartz accuracy means you never have to reset the time.' },
			{ rating: 5, reviewerName: 'Jack Heuer-Vance', review: 'High-contrast black sub-dials over beige-white dial give this piece a golden-era 1969 racing chronograph charm.' },
			{ rating: 4, reviewerName: 'Ben Clymer-Ross', review: 'Solid link steel bracelet with milled clasp feels substantial well beyond its price tier.' },
		],
	},
	{
		name: 'Hamilton Khaki Field Mechanical 38mm Watch',
		brand: 'Hamilton',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'diver-tool-watches',
		description: 'The definitive military field watch built with matte bead-blasted steel case, H-50 hand-winding movement with 80-hour power reserve, and durable NATO strap.',
		variantName: 'Matte Steel White Dial',
		weight: 0.062,
		sizes: [
			{ size: '38mm Hand-Winding', price: 575, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Movement', value: 'Hamilton Exclusive Hand-Wind H-50 Caliber' },
			{ name: 'Power Reserve', value: '80 Hours Extended Power Reserve' },
			{ name: 'Crystal', value: 'Scratch-resistant Sapphire Crystal' },
		],
		photoIds: [
			'1522335789203-aabd1fc54bc9',
			'1524805444758-089113d48a6d',
			'1523275335684-37898b6baf30',
			'1508685096489-7aacd43bd3b1',
			'1533139502658-0198f920d8e8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Captain Miller', review: 'Winding the crown every few mornings becomes a tactile meditative ritual. Ultra-slim 9.5mm case slides under any shirt cuff.' },
			{ rating: 5, reviewerName: 'Cole Hauser-Smith', review: 'Bead-blasted non-reflective finish and high-visibility triangular hour markers are pure utilitarian military perfection.' },
			{ rating: 4, reviewerName: 'James Bond-Vance', review: 'Superb 80-hour power reserve means you can set it down Friday night and pick it up running on Monday.' },
		],
	},
	{
		name: 'Tissot PRX Powermatic 80 Automatic Watch',
		brand: 'Tissot',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'automatic-chronographs',
		description: 'Swiss integrated bracelet icon featuring waffle tapisserie dial, Nivachron anti-magnetic balance spring, and Powermatic 80 automatic movement.',
		variantName: 'Deep Navy Blue Dial',
		weight: 0.138,
		sizes: [
			{ size: '40mm Automatic', price: 725, discount: 0, quantity: 30 },
			{ size: '35mm Automatic', price: 725, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Movement', value: 'Swiss Powermatic 80.111 with Nivachron Spring' },
			{ name: 'Power Reserve', value: 'Up to 80 Hours' },
			{ name: 'Exhibition Back', value: 'Mineral sapphire crystal display caseback' },
		],
		photoIds: [
			'1523275335684-37898b6baf30',
			'1524805444758-089113d48a6d',
			'1508685096489-7aacd43bd3b1',
			'1522335789203-aabd1fc54bc9',
			'1533139502658-0198f920d8e8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Max Büsser', review: 'The integrated stainless steel single-link bracelet catches light like a watch costing ten times as much.' },
			{ rating: 5, reviewerName: 'Silvia Venturini', review: 'Waffle textured tapisserie dial has extraordinary depth and shifts from dark midnight to electric blue under direct sun.' },
			{ rating: 4, reviewerName: 'Jason Heaton', review: 'Exhibition caseback lets you observe the decorated oscillating rotor at work.' },
		],
	},
	{
		name: 'Ray-Ban Classic Original Wayfarer Polarized Sunglasses',
		brand: 'Ray-Ban',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'polarized-eyewear',
		description: 'The most recognizable eyewear style in history crafted in Italy from polished black acetate with crystal green polarized G-15 mineral glass lenses.',
		variantName: 'Polished Black / G-15 Green',
		weight: 0.045,
		sizes: [
			{ size: 'Standard 50mm Eye Size', price: 221, discount: 0, quantity: 40 },
			{ size: 'Large 54mm Eye Size', price: 221, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Lens', value: 'Polarized G-15 Crystal Green Mineral Glass' },
			{ name: 'Frame Material', value: 'High-grade polished Italian cellulose acetate' },
			{ name: 'UV Protection', value: '100% UVA/UVB protection with anti-glare polarization' },
		],
		photoIds: [
			'1511499767150-a48a237f0083',
			'1572635196237-14b3f281503f',
			'1508296695146-257a814070b4',
			'1473496169904-658ba7c44d8a',
			'1577803645773-f96470509666',
		],
		reviews: [
			{ rating: 5, reviewerName: 'John F. Kennedy Jr.', review: 'The forward tilt angle and heavy acetate temples give this silhouette an unforgettable timeless profile.' },
			{ rating: 5, reviewerName: 'Bob Dylan-Smith', review: 'G-15 mineral glass lenses provide crystal-clear optics and eliminate water glare when driving or sailing.' },
			{ rating: 4, reviewerName: 'Audrey Hepburn-Ross', review: 'Solid five-barrel metal hinges open and close with satisfying mechanical tension.' },
		],
	},
	{
		name: 'Bellroy Hide & Seek RFID Leather Wallet',
		brand: 'Bellroy',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'Slim bifold wallet crafted from environmentally certified leather with protected card slots, flat bill section, and hidden cash compartment.',
		variantName: 'Caramel Brown',
		weight: 0.05,
		sizes: [
			{ size: 'Standard Edition (RFID Protected)', price: 89, discount: 0, quantity: 45 },
		],
		specs: [
			{ name: 'Leather', value: 'Certified environmentally rated top-grain leather' },
			{ name: 'Capacity', value: 'Holds 5–12+ cards, flat banknotes, and business cards' },
			{ name: 'Hidden Feature', value: 'Concealed flap compartment for emergency cash backup' },
		],
		photoIds: [
			'1627123424574-724758594e93',
			'1606503829023-e57579730594',
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Andy Fallshaw', review: 'Tapered card slots prevent bulk from stacking at the center. Slides into front jeans pockets invisibly.' },
			{ rating: 5, reviewerName: 'Marcus Aurelius-Smith', review: 'The secret cash flap keeps larger emergency bills hidden from view when paying for routine coffee.' },
			{ rating: 4, reviewerName: 'Hadley Freeman', review: 'The caramel leather develops rich golden honey tones over months of pocket carry.' },
		],
	},
	{
		name: 'Persol 714 Folding Havana Sunglasses',
		brand: 'Persol',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'polarized-eyewear',
		description: 'The world’s first folding sunglasses made legendary by Steve McQueen with patented Meflecto flexible stem system and arrow hinge.',
		variantName: 'Havana Tortoise / Crystal Blue',
		weight: 0.048,
		sizes: [
			{ size: '54mm Eye Size', price: 380, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Folding System', value: '10-step precision folding bridge and temples' },
			{ name: 'Lenses', value: 'Crystal blue polarized mineral glass lenses' },
			{ name: 'Origin', value: 'Handmade in Lauriano, Italy' },
		],
		photoIds: [
			'1511499767150-a48a237f0083',
			'1572635196237-14b3f281503f',
			'1508296695146-257a814070b4',
			'1473496169904-658ba7c44d8a',
			'1577803645773-f96470509666',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Steve McQueen-Smith', review: 'Folds neatly in half into a compact leather pouch that slips into your breast pocket without bulk.' },
			{ rating: 5, reviewerName: 'Marcello Mastroianni', review: 'The Meflecto spring stems eliminate temple pressure for day-long driving comfort.' },
			{ rating: 4, reviewerName: 'Paul Newman-Vance', review: 'The crystal blue lenses enhance contrast while muting blinding reflection glare.' },
		],
	},
	{
		name: 'Nomos Glashütte Tangente 38 Bauhaus Watch',
		brand: 'Nomos Glashütte',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'automatic-chronographs',
		description: 'The design classic of German Bauhaus horology featuring galvanized white silver-plated dial, tempered cornflower blue steel hands, and in-house Alpha caliber.',
		variantName: 'White Silver-Plated Dial',
		weight: 0.048,
		sizes: [
			{ size: '37.5mm Sapphire Caseback', price: 2180, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Movement', value: 'Nomos In-House Manual Alpha Caliber (Made in Glashütte)' },
			{ name: 'Hands', value: 'Thermally blued tempered steel hands' },
			{ name: 'Strap', value: 'Horween Genuine Shell Cordovan Black Leather' },
		],
		photoIds: [
			'1524805444758-089113d48a6d',
			'1522335789203-aabd1fc54bc9',
			'1523275335684-37898b6baf30',
			'1508685096489-7aacd43bd3b1',
			'1533139502658-0198f920d8e8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Roland Schwertner', review: 'Typography and hand proportions are textbook Bauhaus clarity. The in-house Alpha movement is decorated with Glashütte ribbing.' },
			{ rating: 5, reviewerName: 'Walter Gropius-Smith', review: 'The Horween shell cordovan strap is indestructible and molds to the wrist with zero creasing.' },
			{ rating: 4, reviewerName: 'Mies van der Rohe-Vance', review: 'Ultra-thin 6.7mm profile slides under any French cuff. Pure minimalist horology.' },
		],
	},
	{
		name: 'Montblanc Meisterstück Classique Gold-Coated Ballpoint Pen',
		brand: 'Montblanc',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'The pinnacle luxury writing instrument crafted in Hamburg from deep black precious resin with three gold-coated rings and white snowcap emblem.',
		variantName: 'Deep Black Resin / Gold Trim',
		weight: 0.023,
		sizes: [
			{ size: 'Classique Size 164', price: 495, discount: 0, quantity: 30 },
		],
		specs: [
			{ name: 'Barrel & Cap', value: 'Black precious resin inlaid with Montblanc white emblem' },
			{ name: 'Trim', value: 'Three gold-coated rings embossed with Montblanc lettering' },
			{ name: 'Clip', value: 'Gold-coated clip with individual serial number' },
		],
		photoIds: [
			'1583485088034-697b5bc54ccd',
			'1585336261026-777c5e2d1eb1',
			'1585336261026-777c5e2d1eb1',
			'1583485088034-697b5bc54ccd',
			'1627123424574-724758594e93',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Ernest Hemingway-Smith', review: 'Weighted balance centers in the hand effortlessly. The twist mechanism operates with silky German precision.' },
			{ rating: 5, reviewerName: 'Winston Churchill-Vance', review: 'A signature pen for signing contracts and recording journal entries. Refills write smoothly with zero skipping.' },
			{ rating: 4, reviewerName: 'Gabriel Garcia Marquez', review: 'The glossy precious resin has a warm, inviting tactile feel in hand.' },
		],
	},
	{
		name: 'Peak Design Everyday Backpack 20L v2',
		brand: 'Peak Design',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'The iconic photographer and commuter pack with MagLatch hardware, dual weatherproof UltraZips, and modular origami FlexFold dividers.',
		variantName: 'Charcoal Grey',
		weight: 1.66,
		sizes: [
			{ size: '20L Standard', price: 279, discount: 0, quantity: 24 },
			{ size: '30L Extended', price: 319, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Shell Fabric', value: 'Weatherproof 400D double poly-coated DWR nylon' },
			{ name: 'Access', value: 'Top MagLatch + dual weatherproof side zip openings' },
			{ name: 'Organization', value: '3 configurable FlexFold origami dividers + 15" laptop sleeve' },
		],
		photoIds: [
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
			'1577733966973-d680bffd2e80',
			'1581605405669-fcdf81165afa',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Peter Dering', review: 'Dual side access lets you swing the bag around and grab a camera body or water bottle without setting it on wet ground.' },
			{ rating: 5, reviewerName: 'Chris Burkard', review: 'The origami dividers protect delicate camera glass lenses from knocking together in transit.' },
			{ rating: 4, reviewerName: 'Chase Jarvis', review: 'MagLatch closure expands from 17L to 20L easily when packing extra layers.' },
		],
	},
	{
		name: 'Smythson Panama Crossgrain Leather Notebook',
		brand: 'Smythson',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'British heritage pocket journal bound in pliable Panama crossgrain lambskin with gilt-edged featherweight pale blue paper.',
		variantName: 'Nile Blue',
		weight: 0.12,
		sizes: [
			{ size: 'Pocket 9 x 14 cm', price: 95, discount: 0, quantity: 35 },
		],
		specs: [
			{ name: 'Leather', value: 'Crossgrain pliable lambskin leather' },
			{ name: 'Paper', value: '128 leaves of watermarked gilt-edged featherweight paper' },
			{ name: 'Heritage', value: 'Holders of four Royal Warrants of Appointment' },
		],
		photoIds: [
			'1583485088034-697b5bc54ccd',
			'1585336261026-777c5e2d1eb1',
			'1627123424574-724758594e93',
			'1606503829023-e57579730594',
			'1553062407-98eeb64c6a62',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Frank Smythson', review: 'The featherweight pale blue paper holds fountain pen ink without bleeding through to the reverse side.' },
			{ rating: 5, reviewerName: 'Virginia Woolf', review: 'Bends and flexes inside suit jackets without creasing permanently. The gilt edges catch candlelight beautifully.' },
			{ rating: 4, reviewerName: 'Noel Coward', review: 'A refined tactile luxury for jotting down travel thoughts and daily agendas.' },
		],
	},
	{
		name: 'Dents Heritage Unlined Deerskin Leather Driving Gloves',
		brand: 'Dents',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'English driving gloves handmade since 1777 from buttery soft North American deerskin with cutout knuckle vents and elasticized wrist.',
		variantName: 'English Tan',
		weight: 0.08,
		sizes: [
			{ size: 'Size 8.5 (Medium)', price: 165, discount: 0, quantity: 20 },
			{ size: 'Size 9.0 (Large)', price: 165, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Leather', value: '100% Full-Grain North American Deerskin' },
			{ name: 'Venting', value: 'Cutout back, perforated fingers, knuckle holes' },
			{ name: 'Closure', value: 'Dents stud fastener and elastic wrist gather' },
		],
		photoIds: [
			'1627123424574-724758594e93',
			'1606503829023-e57579730594',
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
		],
		reviews: [
			{ rating: 5, reviewerName: 'John Dent-Smith', review: 'Deerskin has natural pebbled elasticity that grips wood and leather steering wheels with extraordinary precision.' },
			{ rating: 5, reviewerName: 'Daniel Craig-Bond', review: 'Unlined construction allows maximum tactile sensitivity. Hand-stitched seam work is flawless.' },
			{ rating: 4, reviewerName: 'Jason Statham-Ross', review: 'The knuckle cutouts keep hands cool during spirited weekend hill climbs.' },
		],
	},
	{
		name: 'Oliver Peoples Gregory Peck Round Frame Sunglasses',
		brand: 'Oliver Peoples',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'polarized-eyewear',
		description: 'Hollywood classic round frame inspired by Gregory Peck in To Kill a Mockingbird with retro keyhole bridge and custom hand-laid plaque hardware.',
		variantName: 'Buff / Green Mineral Lens',
		weight: 0.042,
		sizes: [
			{ size: '47mm Eye Size', price: 440, discount: 0, quantity: 18 },
			{ size: '50mm Eye Size', price: 440, discount: 0, quantity: 22 },
		],
		specs: [
			{ name: 'Frame', value: 'Custom patterned Italian acetate with keyhole bridge' },
			{ name: 'Hinges', value: 'Custom engraved hand-set three-barrel hinges' },
			{ name: 'Lenses', value: 'Breath-logo engraved mineral glass with anti-reflective back coat' },
		],
		photoIds: [
			'1511499767150-a48a237f0083',
			'1572635196237-14b3f281503f',
			'1508296695146-257a814070b4',
			'1473496169904-658ba7c44d8a',
			'1577803645773-f96470509666',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Larry Leight', review: 'The keyhole bridge distributes weight comfortably across narrow and wide nose bridges without pinching.' },
			{ rating: 5, reviewerName: 'Atticus Finch-Smith', review: 'Intellectual vintage charisma that looks distinguished on any face shape. Mineral glass clarity is peerless.' },
			{ rating: 4, reviewerName: 'Harper Lee-Vance', review: 'Subtle buff acetate colorway glows with warmth under sunlight.' },
		],
	},
	{
		name: 'Junghans Max Bill Automatic Minimalist Watch',
		brand: 'Junghans',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'automatic-chronographs',
		description: 'The pure essence of form follows function designed by Bauhaus artist Max Bill in 1961 with domed plexiglass, minimalist typography, and automatic movement.',
		variantName: 'Matte Silver-Plated Dial',
		weight: 0.052,
		sizes: [
			{ size: '38mm Automatic J800.1', price: 1150, discount: 0, quantity: 16 },
		],
		specs: [
			{ name: 'Movement', value: 'Self-winding caliber J800.1 with 38-hour power reserve' },
			{ name: 'Crystal', value: 'Domed sapphire crystal with double anti-reflective coating' },
			{ name: 'Strap', value: 'Vegetable-tanned black calfskin leather' },
		],
		photoIds: [
			'1524805444758-089113d48a6d',
			'1522335789203-aabd1fc54bc9',
			'1523275335684-37898b6baf30',
			'1508685096489-7aacd43bd3b1',
			'1533139502658-0198f920d8e8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Max Bill', review: 'Proportions of dial markers and ultra-thin line hour hands are visual harmony. Extremely legible at any angle.' },
			{ rating: 5, reviewerName: 'Dieter Rams', review: 'As little design as possible. The domed glass creates a lovely optical magnification around the perimeter.' },
			{ rating: 4, reviewerName: 'Otmar Alt', review: 'Smooth automatic winding rotor and comfortable light wrist presence.' },
		],
	},
	{
		name: 'Tanner Goods Classic Full-Grain Leather Belt',
		brand: 'Tanner Goods',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'Handcrafted in Portland, Oregon from 11oz vegetable-tanned Meridian English bridle leather with solid brass roller buckle and Chicago screw hardware.',
		variantName: 'Natural Meridian Tan',
		weight: 0.32,
		sizes: [
			{ size: '32 Waist', price: 125, discount: 0, quantity: 20 },
			{ size: '34 Waist', price: 125, discount: 0, quantity: 30 },
			{ size: '36 Waist', price: 125, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Leather Weight', value: 'Heavyweight 11oz Vegetable-Tanned English Bridle' },
			{ name: 'Hardware', value: 'Solid Machined Brass Roller Buckle' },
			{ name: 'Width', value: '1.25 inches (Standard Trouser / Jean Loop Width)' },
		],
		photoIds: [
			'1627123424574-724758594e93',
			'1606503829023-e57579730594',
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Sam Huff', review: 'Meridian natural leather starts as pale ecru and tans to a rich golden caramel patina with wear.' },
			{ rating: 5, reviewerName: 'Jered Bogli', review: 'Heavy 11oz hide will never stretch or deform around the pin hole. Brass hardware is solid and heavy.' },
			{ rating: 4, reviewerName: 'Mike Giles', review: 'Beveled and hand-burnished edges feel smooth against fine denim waistband loops.' },
		],
	},
	{
		name: 'Rimowa Original Cabin Aluminum Carry-On Luggage',
		brand: 'Rimowa',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'leather-goods',
		description: 'The world’s most recognizable travel suitcase crafted in Cologne from anodized aluminum with signature grooved ribs, Multiwheel system, and TSA lock clasps.',
		variantName: 'Silver Aluminum',
		weight: 4.3,
		sizes: [
			{ size: 'Cabin 35L (Airline Approved)', price: 1430, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Body', value: 'Anodized aluminum alloy with reinforced aluminum corners' },
			{ name: 'Wheel System', value: 'Ball-bearing mounted Multiwheel system with cushioned axels' },
			{ name: 'Security', value: 'Dual TSA-approved combination lock clasps (zipperless)' },
		],
		photoIds: [
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
			'1577733966973-d680bffd2e80',
			'1581605405669-fcdf81165afa',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dieter Morszeck', review: 'The dual ball-bearing wheels glide across airport concourses with zero effort. Zipperless latch closure is secure.' },
			{ rating: 5, reviewerName: 'Alexandre Arnault', review: 'The aluminum shell collects travel scratches and airline stickers like a passport of adventures.' },
			{ rating: 4, reviewerName: 'Virgil Abloh-Smith', review: 'Internal Flex Divider compression packing system keeps shirts wrinkle-free.' },
		],
	},
	{
		name: 'Tom Ford FT5294 Round Optical Eyeglass Frames',
		brand: 'Tom Ford',
		categoryUrl: 'watches-accessories',
		subCategoryUrl: 'polarized-eyewear',
		description: 'Distinguished luxury optical frames handcrafted in Italy from dark havana acetate with signature gold metal T temple inserts and vintage round silhouette.',
		variantName: 'Dark Havana / Shiny Gold T',
		weight: 0.038,
		sizes: [
			{ size: '48mm Eye Size', price: 435, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Frame Material', value: 'Hand-milled Italian cellulose acetate' },
			{ name: 'Signature Detail', value: 'Gold-plated inlaid T temple logo' },
			{ name: 'Origin', value: 'Handcrafted in Italy' },
		],
		photoIds: [
			'1511499767150-a48a237f0083',
			'1572635196237-14b3f281503f',
			'1508296695146-257a814070b4',
			'1473496169904-658ba7c44d8a',
			'1577803645773-f96470509666',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Tom Ford', review: 'The iconic T temple inlay and dark havana grain convey quiet intellectual confidence.' },
			{ rating: 5, reviewerName: 'Colin Firth-Smith', review: 'Fits comfortably on the bridge and takes high-index prescription lenses without distorting the frame shape.' },
			{ rating: 4, reviewerName: 'Nicholas Hoult-Vance', review: 'Substantial acetate weight that sits balanced without sliding down your nose.' },
		],
	},
];
