export interface SeedSize {
	size: string;
	price: number;
	discount: number;
	quantity: number;
}

export interface SeedSpec {
	name: string;
	value: string;
}

export interface SeedReview {
	rating: number;
	review: string;
	reviewerName: string;
}

export interface SeedProductDef {
	name: string;
	brand: string;
	categoryUrl: string;
	subCategoryUrl: string;
	description: string;
	variantName: string;
	weight: number;
	sizes: SeedSize[];
	specs: SeedSpec[];
	photoIds: string[]; // 5 Unsplash photo IDs
	reviews: SeedReview[];
}

export const CATALOG_PART_1: SeedProductDef[] = [
	// ── ELECTRONICS & GADGETS (17 Products) ───────────────────────────────────
	{
		name: 'Keychron Q1 Pro Wireless Mechanical Keyboard',
		brand: 'Keychron',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'laptops-computers',
		description: 'QMK/VIA wireless custom mechanical keyboard engineered with full CNC aluminum body, double-gasket dampening, and hot-swappable sockets.',
		variantName: 'Carbon Black',
		weight: 1.75,
		sizes: [
			{ size: 'Red Linear Switch', price: 199, discount: 0, quantity: 35 },
			{ size: 'Brown Tactile Switch', price: 199, discount: 5, quantity: 42 },
			{ size: 'Banana Switch', price: 209, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Connectivity', value: 'Bluetooth 5.1 & Type-C Wired' },
			{ name: 'Polling Rate', value: '1000 Hz Wired / 90 Hz BT' },
			{ name: 'Plate Material', value: 'Polycarbonate with Sound Absorbing Foam' },
		],
		photoIds: [
			'1587829741301-dc798b83add3',
			'1595225476474-87563907a212',
			'1541140532154-b024d705b909',
			'1511467687858-23d96c32e4ae',
			'1618384887929-16ec33fab9ef',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Marcus Vance', review: 'The double gasket mount gives this keyboard a deep, pleasing acoustic profile. Bluetooth connectivity with my Mac and PC switches in under two seconds.' },
			{ rating: 5, reviewerName: 'Elena Rostova', review: 'Substantial aluminum weight prevents any slipping during fast typing. The pre-lubed brown switches feel buttery smooth.' },
			{ rating: 4, reviewerName: 'Tariq Al-Mansoor', review: 'High build quality. It is quite hefty so definitely meant as a stationary desk piece rather than travel board.' },
		],
	},
	{
		name: 'Sony WH-1000XM5 Noise Canceling Headphones',
		brand: 'Sony',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'audio-headphones',
		description: 'Flagship wireless headphones featuring dual processor noise cancellation, 8 microphones, and ultra-comfortable lightweight synthetic soft fit leather.',
		variantName: 'Silver Platinum',
		weight: 0.25,
		sizes: [
			{ size: 'Standard Edition', price: 398, discount: 10, quantity: 50 },
			{ size: 'Travel Bundle with Adapter', price: 429, discount: 0, quantity: 28 },
		],
		specs: [
			{ name: 'Battery Life', value: 'Up to 30 hours with ANC on' },
			{ name: 'Driver Unit', value: '30mm Carbon Fiber Composite' },
			{ name: 'Codec Support', value: 'LDAC, AAC, SBC' },
		],
		photoIds: [
			'1505740420928-5e560c06d30e',
			'1546435770-a3e426bf472b',
			'1484704849700-f032a568e944',
			'1583394838336-acd977736f90',
			'1524678606370-a47ad25cb82a',
		],
		reviews: [
			{ rating: 5, reviewerName: 'David K.', review: 'Airplane cabin noise was virtually eliminated on my transatlantic flight. Microphones pick up speech clearly even in breezy outdoor conditions.' },
			{ rating: 5, reviewerName: 'Sophia Lin', review: 'Extremely comfortable headband that distributes weight without pressure points. The auto-NC optimizer works reliably in changing environments.' },
			{ rating: 4, reviewerName: 'Liam O’Connor', review: 'Soundstage is crisp with punchy low-end response. App EQ allows precise personal acoustic tuning.' },
		],
	},
	{
		name: 'DJI Mini 4 Pro Fly More Drone System',
		brand: 'DJI',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smart-home-displays',
		description: 'Sub-249g folding camera drone with omnidirectional obstacle sensing, 4K/60fps HDR true vertical shooting, and 20km FHD video transmission.',
		variantName: 'Grey Stealth',
		weight: 0.249,
		sizes: [
			{ size: 'Fly More Combo (RC 2)', price: 1099, discount: 0, quantity: 18 },
			{ size: 'Standard Single Battery', price: 759, discount: 5, quantity: 25 },
		],
		specs: [
			{ name: 'Takeoff Weight', value: '< 249 g' },
			{ name: 'Camera Sensor', value: '1/1.3-inch CMOS with dual native ISO' },
			{ name: 'Max Flight Time', value: '34 minutes (Intelligent Flight Battery)' },
		],
		photoIds: [
			'1508614589041-895b88991e3e',
			'1527977966376-1c8408f9f108',
			'1473968512647-3e447244af8f',
			'1579829366248-204fe8413f31',
			'1517524008697-84bbe3c3fd98',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Gabriel Santos', review: 'ActiveTrack 360 keeps lock on mountain bike trails through dense trees without a single obstacle incident.' },
			{ rating: 5, reviewerName: 'Nadia Thorne', review: 'True vertical shooting delivers clean 4K footage ready for immediate social distribution without resolution cropping.' },
			{ rating: 4, reviewerName: 'Chris Henderson', review: 'The RC 2 controller with built-in screen is bright enough for direct sunlight. Battery management hub charges fast.' },
		],
	},
	{
		name: 'Fujifilm X100VI Digital Rangefinder Camera',
		brand: 'Fujifilm',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smart-home-displays',
		description: 'Iconic fixed-lens rangefinder camera boasting a 40.2MP X-Trans CMOS 5 HR sensor, 6-stop in-body image stabilization, and 20 Film Simulation modes.',
		variantName: 'Silver Classic',
		weight: 0.521,
		sizes: [
			{ size: 'Camera Body Only', price: 1599, discount: 0, quantity: 12 },
			{ size: 'Kit with Weather Resistant Ring', price: 1699, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Sensor', value: '40.2MP X-Trans 5 HR' },
			{ name: 'Lens', value: 'Fujinon 23mm F2.0 (35mm equivalent)' },
			{ name: 'Stabilization', value: '5-Axis In-Body Image Stabilization' },
		],
		photoIds: [
			'1516035069371-29a1b244cc32',
			'1512790182412-b19e6d62bc39',
			'1502920917128-1aa500764cbd',
			'1526170375885-4d8ecf77b99f',
			'1495707902641-75cac588d2e9',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Hannah Meyer', review: 'Film simulations like Reala Ace and Classic Chrome produce JPEG files that require almost zero post-processing.' },
			{ rating: 5, reviewerName: 'Julian Rossi', review: 'The addition of 6-stop IBIS allows hand-held night street photography at shutter speeds down to 1/4 second.' },
			{ rating: 4, reviewerName: 'Devon Clark', review: 'Tactile exposure dials are satisfying and intuitive. Leaf shutter is practically silent during candid street work.' },
		],
	},
	{
		name: 'Logitech MX Master 3S Wireless Performance Mouse',
		brand: 'Logitech',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'laptops-computers',
		description: 'Ergonomic precision mouse with 8K DPI track-on-glass sensor, quiet click switches, and MagSpeed electromagnetic scroll wheel.',
		variantName: 'Pale Grey',
		weight: 0.141,
		sizes: [
			{ size: 'Standard Edition', price: 99, discount: 0, quantity: 60 },
			{ size: 'Bundle with Desk Mat', price: 129, discount: 8, quantity: 35 },
		],
		specs: [
			{ name: 'Sensor Resolution', value: '200 to 8000 DPI' },
			{ name: 'Scroll Wheel', value: 'MagSpeed Electromagnetic with SmartShift' },
			{ name: 'Battery', value: '500mAh Li-Po (up to 70 days)' },
		],
		photoIds: [
			'1615663245857-ac93bb7c39e7',
			'1527864550417-7fd91fc51a46',
			'1586953208448-b95a79798f07',
			'1605792657660-596af9009e82',
			'1587829741301-dc798b83add3',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Arthur Pendelton', review: 'Quiet click buttons eliminate conference call noise while retaining crisp tactile feedback. The horizontal thumb scroll is great for large spreadsheets.' },
			{ rating: 5, reviewerName: 'Kavita Patel', review: 'Tracks flawlessly on our glass boardroom table. Ergonomic thumb rest prevents wrist fatigue over 8-hour design sessions.' },
			{ rating: 4, reviewerName: 'Neil Armstrong Jr.', review: 'Logi Options+ software allows gesture macros that speed up window management and productivity workflows.' },
		],
	},
	{
		name: 'CalDigit TS4 18-Port Thunderbolt 4 Dock',
		brand: 'CalDigit',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'laptops-computers',
		description: 'The definitive Thunderbolt 4 connectivity hub delivering 98W host charging, 2.5GbE Ethernet, 8 USB ports, and dual 6K display support.',
		variantName: 'Anodized Silver',
		weight: 0.64,
		sizes: [
			{ size: 'Standard Hub Unit', price: 399, discount: 0, quantity: 24 },
		],
		specs: [
			{ name: 'Host Charging', value: 'Up to 98W Power Delivery' },
			{ name: 'Total Ports', value: '18 Dedicated I/O Ports' },
			{ name: 'Ethernet', value: '2.5 Gigabit Ethernet (2.5GbE)' },
		],
		photoIds: [
			'1544244015-0df4b3ffc6b0',
			'1517336714731-489689fd1ca8',
			'1496181133206-80ce9b88a853',
			'1525547719571-a2d4ac8945e2',
			'1588872657578-7efd1f1555ed',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Zachary Cole', review: 'One single cable powers my dual 4K studio monitors, audio interface, and charges my MacBook Pro at full 98W rate.' },
			{ rating: 5, reviewerName: 'Samantha Green', review: 'The 2.5GbE port immediately upgraded our local NAS transfer speeds from 110MB/s to nearly 280MB/s.' },
			{ rating: 4, reviewerName: 'Benoit Blanc', review: 'Solid metal chassis acts as an efficient passive heat sink. Zero driver issues across both macOS Sonoma and Windows 11.' },
		],
	},
	{
		name: 'Elgato Stream Deck MK.2 Creative Studio Console',
		brand: 'Elgato',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'laptops-computers',
		description: 'Dynamic 15-key LCD control interface for streamers, video editors, and audio creators with hot-swappable faceplates and one-touch automation macros.',
		variantName: 'Obsidian Matte',
		weight: 0.145,
		sizes: [
			{ size: '15 LCD Keys', price: 149, discount: 0, quantity: 40 },
		],
		specs: [
			{ name: 'Keys', value: '15 customizable tactile LCD keys' },
			{ name: 'Interface', value: 'USB 2.0 detachable Type-C' },
			{ name: 'Stand Angle', value: '45-degree fixed magnetic desktop stand' },
		],
		photoIds: [
			'1550745165-9bc0b252726f',
			'1542751371-adc38448a05e',
			'1511512578047-dfb367046420',
			'1563770660941-20978e870e26',
			'1538481199705-c710c4e965fc',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Tyler B.', review: 'Multi-action macros turn complex video rendering workflows into a single physical keystroke. Plugins for OBS and Spotify work reliably.' },
			{ rating: 5, reviewerName: 'Amara Okafor', review: 'Custom animated icon packs give the desk setup a lively aesthetic while keeping daily shortcuts intuitive.' },
			{ rating: 4, reviewerName: 'Soren Lindqvist', review: 'The angled desktop stand has solid grip and does not slide when tapping keys with authority.' },
		],
	},
	{
		name: 'Anker 737 Power Bank PowerCore 24K',
		brand: 'Anker',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smartphones-mobile',
		description: 'Ultra-powerful 24,000mAh external battery featuring Power Delivery 3.1 and bi-directional 140W fast charging with intelligent smart display.',
		variantName: 'Gunmetal Black',
		weight: 0.63,
		sizes: [
			{ size: '24,000mAh 140W', price: 149, discount: 15, quantity: 38 },
		],
		specs: [
			{ name: 'Capacity', value: '24,000 mAh (86.4 Wh)' },
			{ name: 'Total Output', value: '140W Max via single USB-C port' },
			{ name: 'Display', value: 'Smart Digital Color Screen showing input/output stats' },
		],
		photoIds: [
			'1585338107529-13afc5f02586',
			'1609081219090-a6d81d3085bf',
			'1544716278-ca5e3f4abd8c',
			'1510519138161-58474dfab271',
			'1583394838336-acd977736f90',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Carlos Ramirez', review: 'Charges a 16-inch MacBook Pro at full speed on remote fieldwork trips. The digital display showing real-time wattage draw is very helpful.' },
			{ rating: 5, reviewerName: 'Mira Patel', review: 'Can recharge the power bank itself from 0% to 100% in just 52 minutes using a 140W wall adapter.' },
			{ rating: 4, reviewerName: 'Kenji Sato', review: 'Substantial weight due to the cell count, but fits neatly inside a laptop bag water bottle pocket.' },
		],
	},
	{
		name: 'Shure SM7B Cardioid Dynamic Broadcast Microphone',
		brand: 'Shure',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'audio-headphones',
		description: 'The gold standard studio vocal microphone providing smooth, flat, wide-range frequency response for speech, podcasting, and voiceover.',
		variantName: 'Dark Charcoal',
		weight: 0.765,
		sizes: [
			{ size: 'Microphone Only', price: 399, discount: 0, quantity: 26 },
			{ size: 'Bundle with Cloudlifter CL-1', price: 549, discount: 5, quantity: 18 },
		],
		specs: [
			{ name: 'Polar Pattern', value: 'Cardioid' },
			{ name: 'Frequency Response', value: '50 to 20,000 Hz' },
			{ name: 'Connector', value: 'Three-pin professional XLR' },
		],
		photoIds: [
			'1590658268037-6bf12165a8df',
			'1598488035139-bdbb2231ce04',
			'1519671482749-fd09be7ccebf',
			'1520523839898-507125ef538a',
			'1511671782779-c97d3d27a1d4',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Sean MacIntyre', review: 'Rejects untreated room reflections and keyboard clicks better than any condenser microphone I have owned. Warm vocal presence.' },
			{ rating: 5, reviewerName: 'Rachel Ross', review: 'Built like an absolute tank. The internal shock isolation eliminates boom arm rumble and handling noise.' },
			{ rating: 4, reviewerName: 'Derrick Wu', review: 'Needs a high-gain audio interface or inline preamp like Cloudlifter to shine, but once configured it sounds broadcast ready.' },
		],
	},
	{
		name: 'Sonos Era 300 Spatial Audio Smart Speaker',
		brand: 'Sonos',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'audio-headphones',
		description: 'Revolutionary acoustic architecture delivering Dolby Atmos spatial audio with six drivers angled to direct sound from wall to wall and floor to ceiling.',
		variantName: 'Matte White',
		weight: 4.47,
		sizes: [
			{ size: 'Single Speaker', price: 449, discount: 0, quantity: 30 },
			{ size: 'Stereo Pair Set (2x)', price: 849, discount: 5, quantity: 12 },
		],
		specs: [
			{ name: 'Amplification', value: 'Six class-D digital amplifiers' },
			{ name: 'Spatial Audio', value: 'Dolby Atmos Music & Trueplay tuning' },
			{ name: 'Connectivity', value: 'Wi-Fi 6, Bluetooth 5.0, USB-C Line-In' },
		],
		photoIds: [
			'1545454675-3531b543be5d',
			'1518444065439-e933c06cebce',
			'1512446816042-444d641267d4',
			'1508700115892-45ecd05ae2ad',
			'1524678606370-a47ad25cb82a',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Vincent Morel', review: 'Listening to spatial audio tracks on Apple Music feels like being surrounded by the band inside an auditorium.' },
			{ rating: 5, reviewerName: 'Laura Christensen', review: 'Trueplay calibration tuned the output to our asymmetric open-plan living room in minutes with clear acoustic separation.' },
			{ rating: 4, reviewerName: 'Oliver Twist', review: 'Modern hourglass profile looks sculptural on our credenza. Multi-room sync with our soundbar is instantaneous.' },
		],
	},
	{
		name: 'Apple iPad Air M2 11-Inch Liquid Retina',
		brand: 'Apple',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smartphones-mobile',
		description: 'Supercharged by the M2 chip with an 11-inch Liquid Retina display, landscape front camera with Center Stage, and superfast Wi-Fi 6E connectivity.',
		variantName: 'Starlight Aluminum',
		weight: 0.462,
		sizes: [
			{ size: '128GB Wi-Fi', price: 599, discount: 0, quantity: 45 },
			{ size: '256GB Wi-Fi', price: 699, discount: 5, quantity: 30 },
			{ size: '512GB Wi-Fi + Cellular', price: 999, discount: 0, quantity: 16 },
		],
		specs: [
			{ name: 'Processor', value: 'Apple M2 8-core CPU / 10-core GPU' },
			{ name: 'Display', value: '11-inch Liquid Retina with True Tone and P3 wide color' },
			{ name: 'Camera', value: '12MP Ultra Wide landscape front camera' },
		],
		photoIds: [
			'1544244015-0df4b3ffc6b0',
			'1561154464-82e9adf32764',
			'1585792180666-f75a7c3ab27c',
			'1546868871-7041f2a55e12',
			'1517336714731-489689fd1ca8',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Chloe Bennett', review: 'The landscape front camera position makes Zoom meetings look natural without having to gaze off to the side.' },
			{ rating: 5, reviewerName: 'Jonathan Rivera', review: 'M2 handles 4K timeline scrub and complex Lightroom RAW exports effortlessly with zero thermal throttling.' },
			{ rating: 4, reviewerName: 'Evelyn Taylor', review: 'Pencil Pro integration with squeeze gestures speeds up sketching and PDF markup workflows significantly.' },
		],
	},
	{
		name: 'Marshall Stanmore III Bluetooth Home Speaker',
		brand: 'Marshall',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'audio-headphones',
		description: 'Vintage-inspired home audio legend delivering immersive room-filling stereo sound, outward-angled tweeters, and signature brass control knobs.',
		variantName: 'Vintage Cream',
		weight: 4.25,
		sizes: [
			{ size: 'Standard Home Unit', price: 379, discount: 0, quantity: 22 },
		],
		specs: [
			{ name: 'Frequency Range', value: '45–20,000 Hz' },
			{ name: 'Bluetooth', value: 'Bluetooth 5.2 with LE Audio readiness' },
			{ name: 'Inputs', value: '3.5 mm AUX, RCA, Bluetooth' },
		],
		photoIds: [
			'1545454675-3531b543be5d',
			'1512446816042-444d641267d4',
			'1508700115892-45ecd05ae2ad',
			'1518444065439-e933c06cebce',
			'1524678606370-a47ad25cb82a',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Gareth Brooks', review: 'The physical brass knobs for bass, treble, and volume feel tactile and enjoyable to dial in. Deep, resonant rock soundstage.' },
			{ rating: 5, reviewerName: 'Monique Laurent', review: 'Vintage tolex and fret grill cloth looks stunning on our record player stand. Vocals sound warm and textured.' },
			{ rating: 4, reviewerName: 'Felix Baum', review: 'Loud enough to power a lively dinner gathering without distortion at higher volume thresholds.' },
		],
	},
	{
		name: 'Belkin BoostCharge Pro 3-in-1 MagSafe Stand',
		brand: 'Belkin',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smartphones-mobile',
		description: 'Apple-certified 15W wireless fast-charging dock powering iPhone, Apple Watch Ultra, and AirPods simultaneously with architectural stainless steel arms.',
		variantName: 'Charcoal Black',
		weight: 0.81,
		sizes: [
			{ size: '3-in-1 Charging Stand', price: 149, discount: 0, quantity: 45 },
		],
		specs: [
			{ name: 'Wireless Standard', value: 'Official MagSafe 15W + Fast Watch Module' },
			{ name: 'Material', value: 'High-Grade Stainless Steel & Silicone Base' },
			{ name: 'Compatibility', value: 'iPhone 12 through 16, Apple Watch Series 7+, AirPods' },
		],
		photoIds: [
			'1585338107529-13afc5f02586',
			'1510519138161-58474dfab271',
			'1544716278-ca5e3f4abd8c',
			'1609081219090-a6d81d3085bf',
			'1615663245857-ac93bb7c39e7',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Trevor Phillips', review: 'Heavy weighted base ensures the stand never lifts up when detaching your iPhone from the magnetic ring.' },
			{ rating: 5, reviewerName: 'Ashley Miller', review: 'Watch fast-charger tops off my Apple Watch Series 9 from 20% to 80% in approximately 35 minutes while showering.' },
			{ rating: 4, reviewerName: 'Daniel Craigson', review: 'Clean cable management leaves just a single minimalist power plug to hide on the nightstand.' },
		],
	},
	{
		name: 'GoPro HERO12 Black Waterproof Action Camera',
		brand: 'GoPro',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smart-home-displays',
		description: 'Rugged 5.3K60 HDR video action camera featuring Emmy-winning HyperSmooth 6.0 stabilization, vertical capture mode, and wireless Bluetooth audio support.',
		variantName: 'Matte Rugged Black',
		weight: 0.154,
		sizes: [
			{ size: 'Standard Action Kit', price: 399, discount: 10, quantity: 32 },
			{ size: 'Creator Edition with Grip', price: 599, discount: 0, quantity: 14 },
		],
		specs: [
			{ name: 'Video Resolution', value: '5.3K at 60fps / 4K at 120fps' },
			{ name: 'Stabilization', value: 'HyperSmooth 6.0 with 360-degree Horizon Lock' },
			{ name: 'Waterproofing', value: 'Rugged submersible to 33ft (10m)' },
		],
		photoIds: [
			'1526170375885-4d8ecf77b99f',
			'1516035069371-29a1b244cc32',
			'1502920917128-1aa500764cbd',
			'1512790182412-b19e6d62bc39',
			'1495707902641-75cac588d2e9',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Jack Reynolds', review: 'Horizon lock keeps downhill snowboarding footage rock-steady even through full 360 degree rotational flips.' },
			{ rating: 5, reviewerName: 'Maya Patel', review: 'HDR video mode balances bright ski snow and dark shaded pine trees without blown-out highlight clipping.' },
			{ rating: 4, reviewerName: 'Austin Cole', review: 'Bluetooth microphone support let us record clean commentary through wireless earbuds without external dongles.' },
		],
	},
	{
		name: 'Kindle Paperwhite Signature Edition 32GB',
		brand: 'Amazon',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'smart-home-displays',
		description: 'Purpose-built reading tablet with 6.8-inch glare-free 300 ppi display, auto-adjusting warm front light, wireless charging, and up to 10 weeks battery life.',
		variantName: 'Agave Green',
		weight: 0.207,
		sizes: [
			{ size: '32GB Wireless Charging', price: 189, discount: 5, quantity: 40 },
		],
		specs: [
			{ name: 'Display', value: '6.8-inch Paperwhite with flush-front design' },
			{ name: 'Resolution', value: '300 ppi glare-free E-ink' },
			{ name: 'Battery', value: 'Up to 10 weeks on single charge' },
		],
		photoIds: [
			'1544716278-ca5e3f4abd8c',
			'1510519138161-58474dfab271',
			'1561154464-82e9adf32764',
			'1585792180666-f75a7c3ab27c',
			'1546868871-7041f2a55e12',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Beatrice Ward', review: 'The amber warm light makes reading in complete darkness comfortable with zero blue-light eye strain.' },
			{ rating: 5, reviewerName: 'Lucas Campbell', review: 'Battery life is astonishing. I read an hour every evening and only plug it in once every two months.' },
			{ rating: 4, reviewerName: 'Penelope Cruz-Smith', review: 'Waterproof build gives peace of mind when reading by the pool or in the bath. Page turns are crisp and fast.' },
		],
	},
	{
		name: 'Nothing Ear Wireless Earbuds Hi-Res Audio',
		brand: 'Nothing',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'audio-headphones',
		description: 'Iconic transparent acoustic earbuds featuring ceramic drivers, 45dB smart active noise cancellation, and LDAC high-resolution sound certification.',
		variantName: 'Clear Crystal White',
		weight: 0.052,
		sizes: [
			{ size: 'Standard Earbuds with Case', price: 149, discount: 0, quantity: 50 },
		],
		specs: [
			{ name: 'Driver', value: '11mm custom ceramic driver' },
			{ name: 'Noise Cancellation', value: 'Up to 45dB Smart Active Noise Cancellation' },
			{ name: 'Playback', value: 'Up to 40.5 hours with charging case' },
		],
		photoIds: [
			'1590658268037-6bf12165a8df',
			'1505740420928-5e560c06d30e',
			'1546435770-a3e426bf472b',
			'1484704849700-f032a568e944',
			'1583394838336-acd977736f90',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dante Moretti', review: 'The ceramic drivers produce extraordinary high-frequency detail on acoustic guitars and hi-hats without harshness.' },
			{ rating: 5, reviewerName: 'Sarah Jenkins', review: 'Transparent case design is visually striking. The pinch controls avoid accidental trigger events when readjusting.' },
			{ rating: 4, reviewerName: 'Tomo Tanaka', review: 'Dual-connection multipoint pairs seamlessly between laptop and phone. Microphone call quality is very clear.' },
		],
	},
	{
		name: 'BenQ ScreenBar Halo Monitor Light with Wireless Controller',
		brand: 'BenQ',
		categoryUrl: 'electronics-gadgets',
		subCategoryUrl: 'laptops-computers',
		description: 'Advanced desktop monitor lamp with patented asymmetrical optical design, ambient backlight illumination, and precision wireless desktop dial.',
		variantName: 'Metallic Space Grey',
		weight: 0.8,
		sizes: [
			{ size: 'ScreenBar Halo + Dial', price: 179, discount: 0, quantity: 28 },
		],
		specs: [
			{ name: 'Optical Design', value: 'Asymmetrical non-glare illumination' },
			{ name: 'Backlight', value: 'Independent ambient rear illumination' },
			{ name: 'Controller', value: '2.4GHz wireless touch rotary dial' },
		],
		photoIds: [
			'1517336714731-489689fd1ca8',
			'1496181133206-80ce9b88a853',
			'1525547719571-a2d4ac8945e2',
			'1588872657578-7efd1f1555ed',
			'1587829741301-dc798b83add3',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Evan Wright', review: 'Directs light downward onto the workspace with zero screen reflections or glare. Saves valuable desk surface space.' },
			{ rating: 5, reviewerName: 'Natalia V.', review: 'The wireless rotary controller has smooth resistance and lets you tweak brightness and warmth in seconds.' },
			{ rating: 4, reviewerName: 'George Sterling', review: 'Rear ambient backlight balances room contrast during late-night coding sessions and reduces eye fatigue.' },
		],
	},

	// ── FASHION & APPAREL (17 Products) ───────────────────────────────────────
	{
		name: 'Barbour Classic Beaufort Waxed Cotton Jacket',
		brand: 'Barbour',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-outerwear',
		description: 'Timeless British country outerwear crafted in South Shields from mediumweight 6oz Thornproof waxed cotton with signature corduroy collar and tartan lining.',
		variantName: 'Olive Green',
		weight: 1.45,
		sizes: [
			{ size: '38 Regular', price: 445, discount: 0, quantity: 15 },
			{ size: '40 Regular', price: 445, discount: 0, quantity: 20 },
			{ size: '42 Regular', price: 445, discount: 0, quantity: 18 },
			{ size: '44 Regular', price: 445, discount: 0, quantity: 10 },
		],
		specs: [
			{ name: 'Shell Material', value: '100% 6oz Sylkoil Waxed Cotton' },
			{ name: 'Lining', value: '100% Cotton Classic Barbour Tartan' },
			{ name: 'Closure', value: 'Heavy-duty two-way brass zip with storm fly front' },
		],
		photoIds: [
			'1551028719-00167b16eac5',
			'1544441893-675973e31985',
			'1516257984-b1b4d707412e',
			'1489987707025-afc232f7ea0f',
			'1576995853123-5a10305d93c0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Charles Montgomery', review: 'An enduring wardrobe cornerstone. Sheds heavy rain effortlessly and the large rear game pocket is surprisingly practical.' },
			{ rating: 5, reviewerName: 'Angus MacLeod', review: 'Substantial brass zippers and deep moleskin handwarmer pockets. The waxed cotton develops rich character over seasons.' },
			{ rating: 4, reviewerName: 'Simon Hayes', review: 'Relaxed traditional cut allows room for thick Shetland wool knitwear underneath.' },
		],
	},
	{
		name: 'Red Wing Heritage Iron Ranger 6-Inch Boots',
		brand: 'Red Wing',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'athletic-footwear',
		description: 'Legendary American work boot built with oil-tanned Amber Harness full-grain leather, Goodyear welt construction, and rugged Vibram 430 Mini-Lug outsoles.',
		variantName: 'Amber Harness',
		weight: 1.85,
		sizes: [
			{ size: 'US 8.5 D', price: 349, discount: 0, quantity: 12 },
			{ size: 'US 9.0 D', price: 349, discount: 0, quantity: 22 },
			{ size: 'US 10.0 D', price: 349, discount: 0, quantity: 25 },
			{ size: 'US 11.0 D', price: 349, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Leather Type', value: 'Oil-tanned full grain Amber Harness' },
			{ name: 'Construction', value: 'Goodyear Welt with triple-stitched seams' },
			{ name: 'Outsole', value: 'Vibram 430 Mini-Lug' },
		],
		photoIds: [
			'1520639888713-7851133b1ed0',
			'1542291026-7eec264c27ff',
			'1608256246200-53e635b5b65f',
			'1560769629-975ec94e6a86',
			'1595950653106-6c9ebd614d3a',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Wyatt Earp Jr.', review: 'Takes a couple of weeks to mold to your foot shape, but once the thick leather insole breaks in, they fit like custom gloves.' },
			{ rating: 5, reviewerName: 'Cole Hauser', review: 'Heavy-duty steel shank and double-layer toe cap. Resoleable Goodyear construction ensures decades of use.' },
			{ rating: 4, reviewerName: 'Mason Briggs', review: 'Stunning amber patina forms rapidly with simple conditioner treatment. Order half size down from typical sneaker size.' },
		],
	},
	{
		name: 'Levi’s Vintage Clothing 1954 501 Original Selvedge Jeans',
		brand: 'Levi’s',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'Faithful historical recreation of the 1954 zip-fly 501 cut from raw Kaihara Japanese selvedge denim with classic tapered leg profile.',
		variantName: 'Rigid Indigo',
		weight: 0.85,
		sizes: [
			{ size: '30x32', price: 265, discount: 0, quantity: 14 },
			{ size: '32x32', price: 265, discount: 0, quantity: 25 },
			{ size: '34x32', price: 265, discount: 0, quantity: 20 },
			{ size: '36x32', price: 265, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Denim Weight', value: '12oz Cone Mills / Kaihara Raw Selvedge' },
			{ name: 'Fit Profile', value: 'Regular rise with gentle taper from knee to hem' },
			{ name: 'Details', value: 'Big E red tab, copper rivets, hidden back pocket rivets' },
		],
		photoIds: [
			'1541099649105-f69ad21f3246',
			'1542272604-787c3835535d',
			'1582552938357-32b906dfca0f',
			'1576995853123-5a10305d93c0',
			'1489987707025-afc232f7ea0f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Julian Thorne', review: 'The selvedge ID roll looks clean on cuffs. The raw unwashed denim yields sharp honeycombs and whiskering within six months.' },
			{ rating: 5, reviewerName: 'Dennis Ritchie', review: 'Authentic 1950s silhouette that strikes the right balance between timeless vintage style and tailored modern fit.' },
			{ rating: 4, reviewerName: 'Alex Mercer', review: 'Expect around 1-inch of shrink-to-fit settling after the initial cold soak, exactly as traditional raw denim should.' },
		],
	},
	{
		name: 'Patagonia Better Sweater Fleece Zip Jacket',
		brand: 'Patagonia',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-outerwear',
		description: 'Cozy sweater-knit fleece jacket made from 100% recycled polyester with low-impact dyeing process, raglan sleeves, and zip-through stand-up collar.',
		variantName: 'Stonewash Heather',
		weight: 0.638,
		sizes: [
			{ size: 'Small', price: 159, discount: 0, quantity: 18 },
			{ size: 'Medium', price: 159, discount: 0, quantity: 30 },
			{ size: 'Large', price: 159, discount: 0, quantity: 28 },
			{ size: 'X-Large', price: 159, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Material', value: '100% Recycled Polyester Sweater-Knit Fleece' },
			{ name: 'Certification', value: 'Fair Trade Certified Sewn' },
			{ name: 'Pockets', value: 'Zippered handwarmers and vertical security chest pocket' },
		],
		photoIds: [
			'1551028719-00167b16eac5',
			'1516257984-b1b4d707412e',
			'1544441893-675973e31985',
			'1489987707025-afc232f7ea0f',
			'1576995853123-5a10305d93c0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Brett Collins', review: 'Soft brushed interior keeps you warm without bulk. The flat-seam construction prevents any chafing under a pack.' },
			{ rating: 5, reviewerName: 'Kara Danvers', review: 'Holds up through frequent machine washes without pilling. Perfect mid-layer for brisk autumn hikes.' },
			{ rating: 4, reviewerName: 'Paul Stewart', review: 'Sweater-knit outer face looks smart enough for casual office meetings while delivering outdoor performance.' },
		],
	},
	{
		name: 'Norse Projects Anton Oxford Cotton Shirt',
		brand: 'Norse Projects',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'Scandinavian minimalist button-down collar shirt woven in Portugal from dense three-ply Oxford cotton with Mother of Pearl buttons.',
		variantName: 'Clean White',
		weight: 0.32,
		sizes: [
			{ size: 'Small', price: 185, discount: 0, quantity: 20 },
			{ size: 'Medium', price: 185, discount: 0, quantity: 35 },
			{ size: 'Large', price: 185, discount: 0, quantity: 30 },
			{ size: 'X-Large', price: 185, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Fabric', value: '100% 3-Ply Cotton Oxford Cloth' },
			{ name: 'Buttons', value: 'Genuine Mother of Pearl' },
			{ name: 'Origin', value: 'Woven & Tailored in Portugal' },
		],
		photoIds: [
			'1596755094514-f87e34085b2c',
			'1602810318383-e386cc2a3ccf',
			'1521572267360-ee0c2909d518',
			'1598033129183-c4f50c736f10',
			'1503342217505-b0a15ec3261c',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Lars Mikkelsen', review: 'Dense Oxford cloth with crisp collar roll. Drapes naturally without requiring heavy starching.' },
			{ rating: 5, reviewerName: 'Christian Wolff', review: 'Impeccable seam stitching and durable shell buttons. Fits trim across shoulders with comfortable chest allowance.' },
			{ rating: 4, reviewerName: 'Andrew Scott', review: 'Substantial fabric weight that softens with each laundry cycle while holding its structured silhouette.' },
		],
	},
	{
		name: 'Reigning Champ Midweight French Terry Hoodie',
		brand: 'Reigning Champ',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'Handcrafted Canadian fleece pullover hoodie constructed with flatlocked seams, set-in/raglan sleeves, and rib-bound patch pocket.',
		variantName: 'Heather Ash Grey',
		weight: 0.72,
		sizes: [
			{ size: 'Small', price: 165, discount: 0, quantity: 15 },
			{ size: 'Medium', price: 165, discount: 0, quantity: 28 },
			{ size: 'Large', price: 165, discount: 0, quantity: 25 },
			{ size: 'X-Large', price: 165, discount: 0, quantity: 14 },
		],
		specs: [
			{ name: 'Fleece Type', value: '100% Cotton Midweight French Terry' },
			{ name: 'Construction', value: 'Flatlock stitched with rib side panels' },
			{ name: 'Origin', value: 'Made in Vancouver, Canada' },
		],
		photoIds: [
			'1556905055-8f358a7a47b2',
			'1509631179647-0177331693ae',
			'1515886657613-9f3515b0c78f',
			'1529139574466-a303027c1d8b',
			'1489987707025-afc232f7ea0f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Derek Frost', review: 'The heavyweight ribbed side gussets make movement effortless without causing the hoodie to box out.' },
			{ rating: 5, reviewerName: 'Nathan Drake', review: 'Built for longevity. After dozens of washes, the cuffs stay tight and the French terry remains plush.' },
			{ rating: 4, reviewerName: 'Gabe Newell', review: 'Double-lined hood holds structured shape when up or resting on shoulders.' },
		],
	},
	{
		name: 'Common Projects Original Achilles Low Sneakers',
		brand: 'Common Projects',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'athletic-footwear',
		description: 'The definitive minimalist sneaker handcrafted in Italy from smooth nappa leather with gold foil serial number stamp and stitched Margom rubber cupsole.',
		variantName: 'Optic White',
		weight: 0.95,
		sizes: [
			{ size: 'EU 40', price: 440, discount: 0, quantity: 10 },
			{ size: 'EU 41', price: 440, discount: 0, quantity: 18 },
			{ size: 'EU 42', price: 440, discount: 0, quantity: 24 },
			{ size: 'EU 43', price: 440, discount: 0, quantity: 20 },
			{ size: 'EU 44', price: 440, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Upper Material', value: '100% Italian Nappa Calfskin' },
			{ name: 'Sole', value: 'Stitched Margom Italian Rubber Cupsole' },
			{ name: 'Signature Detail', value: 'Gold stamped style, size, and color code' },
		],
		photoIds: [
			'1549298916-b41d501d3772',
			'1560769629-975ec94e6a86',
			'1595950653106-6c9ebd614d3a',
			'1542291026-7eec264c27ff',
			'1608256246200-53e635b5b65f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Matteo Rossi', review: 'Unrivaled silhouette profile. Looks equally refined paired with tailored trousers or casual selvedge denim.' },
			{ rating: 5, reviewerName: 'Oliver Twist', review: 'Full leather lining and supple calfskin break in naturally over a weekend of city walking.' },
			{ rating: 4, reviewerName: 'Ken Adams', review: 'Understated elegance with subtle gold heel stamping. Size down one full European size for optimal fit.' },
		],
	},
	{
		name: 'Filson Rugged Twill Medium Duffle Bag',
		brand: 'Filson',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'bags-backpacks',
		description: 'Heirloom travel duffle constructed in Seattle from industrial water-resistant Rugged Twill and vegetable-tanned Bridle Leather straps with solid brass hardware.',
		variantName: 'Otter Green',
		weight: 1.68,
		sizes: [
			{ size: '43L Medium', price: 495, discount: 0, quantity: 16 },
		],
		specs: [
			{ name: 'Body Fabric', value: '100% Cotton 14oz Rugged Twill' },
			{ name: 'Leather Trim', value: 'Vegetable-tanned Saddle Bridle Leather' },
			{ name: 'Hardware', value: 'Solid sand-cast brass with heavy-duty zipper' },
		],
		photoIds: [
			'1553062407-98eeb64c6a62',
			'1622560480605-d83c853bc5c3',
			'1546938576-6e6a64f317cc',
			'1577733966973-d680bffd2e80',
			'1581605405669-fcdf81165afa',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Harrison Vance', review: 'Indestructible construction. Has survived airline baggage carousels and backcountry float planes without a frayed thread.' },
			{ rating: 5, reviewerName: 'Cole Sterling', review: 'Bridle leather shoulder pad distributes weight smoothly. The storm flap zipper keeps contents dry in Pacific Northwest drizzle.' },
			{ rating: 4, reviewerName: 'Arthur Dent', review: 'Heavy empty weight because of the industrial twill and brass, but it is built to outlast a lifetime.' },
		],
	},
	{
		name: 'Arc’teryx Atom Heavyweight Insulated Hoody',
		brand: 'Arc’teryx',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-outerwear',
		description: 'Versatile alpine mid-layer delivering Coreloft synthetic insulation, weather-resistant Tyono 30 outer face, and breathable stretch fleece side panels.',
		variantName: 'Black Sapphire',
		weight: 0.475,
		sizes: [
			{ size: 'Small', price: 350, discount: 0, quantity: 18 },
			{ size: 'Medium', price: 350, discount: 0, quantity: 28 },
			{ size: 'Large', price: 350, discount: 0, quantity: 24 },
			{ size: 'X-Large', price: 350, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Insulation', value: 'Coreloft 120/80/60 g/m² Body-Mapped Synthetic' },
			{ name: 'Face Fabric', value: 'Tyono 30 Denier with DWR finish' },
			{ name: 'Hood', value: 'Insulated, helmet-compatible StormHood' },
		],
		photoIds: [
			'1551028719-00167b16eac5',
			'1516257984-b1b4d707412e',
			'1544441893-675973e31985',
			'1489987707025-afc232f7ea0f',
			'1576995853123-5a10305d93c0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Erik Lindstrom', review: 'The warmth-to-weight ratio is unmatched. Breathable underarm stretch panels prevent overheating on steep trail ascents.' },
			{ rating: 5, reviewerName: 'Silvia Rossi', review: 'Retains loft and thermal warmth even when damp from sleet. The StormHood cinches snugly with single-cord adjustment.' },
			{ rating: 4, reviewerName: 'Devon Ward', review: 'Articulated elbows give full range of motion while climbing or scrambling.' },
		],
	},
	{
		name: 'Sunspel Classic Organic Cotton Crewneck T-Shirt',
		brand: 'Sunspel',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'The archetype English luxury tee crafted since 1908 from two-fold long-staple organic Supima cotton for exceptional softness and shape retention.',
		variantName: 'Navy Blue',
		weight: 0.18,
		sizes: [
			{ size: 'Small', price: 95, discount: 0, quantity: 30 },
			{ size: 'Medium', price: 95, discount: 0, quantity: 45 },
			{ size: 'Large', price: 95, discount: 0, quantity: 40 },
			{ size: 'X-Large', price: 95, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Yarn', value: '2-Ply Long-Staple California Supima Cotton' },
			{ name: 'Neckline', value: 'Bound ribbed crew collar' },
			{ name: 'Origin', value: 'Handmade in Long Eaton, England' },
		],
		photoIds: [
			'1521572267360-ee0c2909d518',
			'1503342217505-b0a15ec3261c',
			'1598033129183-c4f50c736f10',
			'1596755094514-f87e34085b2c',
			'1602810318383-e386cc2a3ccf',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Jonathan Pierce', review: 'The jersey weave is silky smooth with zero loose fibers. Holds its neckline shape wash after wash without bacon-neck curling.' },
			{ rating: 5, reviewerName: 'Martin King', review: 'Lightweight and breathable under summer linen jackets. Quality is evident from the first touch.' },
			{ rating: 4, reviewerName: 'Sean Connolly', review: 'Tailored fit that contours the chest and shoulders without being overly restrictive.' },
		],
	},
	{
		name: 'Ralph Lauren Cable-Knit Wool-Cashmere Sweater',
		brand: 'Ralph Lauren',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'Iconic Ivy League heritage knitwear blending Italian wool and cashmere with classic allover cable pattern and ribbed trim.',
		variantName: 'Hunter Navy',
		weight: 0.54,
		sizes: [
			{ size: 'Small', price: 248, discount: 0, quantity: 18 },
			{ size: 'Medium', price: 248, discount: 0, quantity: 26 },
			{ size: 'Large', price: 248, discount: 0, quantity: 24 },
			{ size: 'X-Large', price: 248, discount: 0, quantity: 14 },
		],
		specs: [
			{ name: 'Composition', value: '90% Italian Wool, 10% Cashmere' },
			{ name: 'Knit Style', value: 'Traditional 7-Gauge Dimensional Cable' },
			{ name: 'Embroidery', value: 'Signature tonal pony embroidered at left chest' },
		],
		photoIds: [
			'1556905055-8f358a7a47b2',
			'1509631179647-0177331693ae',
			'1515886657613-9f3515b0c78f',
			'1529139574466-a303027c1d8b',
			'1489987707025-afc232f7ea0f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Preston Brooks', review: 'The 10% cashmere addition eliminates itchiness while retaining the structural warmth of pure Italian wool.' },
			{ rating: 5, reviewerName: 'Edward Thorne', review: 'Rich cable relief texture that looks sharp layered over a crisp collared button-down.' },
			{ rating: 4, reviewerName: 'Christopher Bell', review: 'True to heritage sizing. Ribbed waist and cuffs stay snug without riding up.' },
		],
	},
	{
		name: 'Taylor Stitch The Camp Pant in Heavy Corduroy',
		brand: 'Taylor Stitch',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'Rugged utility trousers crafted from burly 10-wale organic cotton corduroy with reinforced knee panels and custom antique brass pocket rivets.',
		variantName: 'Caramel British Cord',
		weight: 0.78,
		sizes: [
			{ size: '30 Waist', price: 148, discount: 0, quantity: 16 },
			{ size: '32 Waist', price: 148, discount: 0, quantity: 28 },
			{ size: '34 Waist', price: 148, discount: 0, quantity: 25 },
			{ size: '36 Waist', price: 148, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Material', value: '100% Organic Cotton 10-Wale Corduroy' },
			{ name: 'Hardware', value: 'Custom YKK brass button-fly and pocket rivets' },
			{ name: 'Pockets', value: 'Double-welted rear pockets and curved front slash pockets' },
		],
		photoIds: [
			'1541099649105-f69ad21f3246',
			'1542272604-787c3835535d',
			'1582552938357-32b906dfca0f',
			'1576995853123-5a10305d93c0',
			'1489987707025-afc232f7ea0f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Gabe Vance', review: 'The 10-wale cord has deep ridges and substantial hand-feel. Keeps your legs warm on blustery autumn commutes.' },
			{ rating: 5, reviewerName: 'Noah Sterling', review: 'Curved front pocket entry makes retrieving EDC pocket knives or keys seamless while seated.' },
			{ rating: 4, reviewerName: 'Logan Meyer', review: 'Straight relaxed leg profile works naturally over heavy work boots or casual trainers.' },
		],
	},
	{
		name: 'Blundstone Original 500 Leather Chelsea Boots',
		brand: 'Blundstone',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'athletic-footwear',
		description: 'Tasmanian heritage slip-on Chelsea boot featuring weatherproof Stout Brown leather, XRD heel strike shock absorption, and dual pull-tabs.',
		variantName: 'Stout Brown',
		weight: 1.15,
		sizes: [
			{ size: 'AU 7 (US 8)', price: 219, discount: 0, quantity: 18 },
			{ size: 'AU 8 (US 9)', price: 219, discount: 0, quantity: 30 },
			{ size: 'AU 9 (US 10)', price: 219, discount: 0, quantity: 28 },
			{ size: 'AU 10 (US 11)', price: 219, discount: 0, quantity: 16 },
		],
		specs: [
			{ name: 'Leather', value: '2.5mm Oiled Weatherproof Leather' },
			{ name: 'Sole', value: 'Thermo-urethane outsole resistant to hydrolysis' },
			{ name: 'Shock System', value: 'XRD Technology in the heel strike zone' },
		],
		photoIds: [
			'1520639888713-7851133b1ed0',
			'1608256246200-53e635b5b65f',
			'1560769629-975ec94e6a86',
			'1595950653106-6c9ebd614d3a',
			'1542291026-7eec264c27ff',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Liam Kelly', review: 'My everyday shoe from October through April. Water and mud wipe clean with a wet towel and the elastic gussets never lose snap.' },
			{ rating: 5, reviewerName: 'Clara Oswald', review: 'Shock-absorbing heel pad makes standing on concrete studio floors completely fatigue-free.' },
			{ rating: 4, reviewerName: 'Evan Peters', review: 'Dual branded pull tabs make slipping in and out instantaneous. Rugged yet timeless.' },
		],
	},
	{
		name: 'Engineered Garments Aviator Flight Jacket',
		brand: 'Engineered Garments',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-outerwear',
		description: 'New York utilitarian MA-1 flight jacket crafted in lightweight flight satin nylon with two-way asymmetric zipper and military utility sleeve pocket.',
		variantName: 'Deep Olive Satin',
		weight: 0.88,
		sizes: [
			{ size: 'Small', price: 585, discount: 0, quantity: 8 },
			{ size: 'Medium', price: 585, discount: 0, quantity: 14 },
			{ size: 'Large', price: 585, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Shell', value: 'High-Density Flight Nylon Satin' },
			{ name: 'Lining', value: 'Quilted PrimaLoft Thermal Core' },
			{ name: 'Origin', value: 'Designed & Manufactured in New York City' },
		],
		photoIds: [
			'1551028719-00167b16eac5',
			'1544441893-675973e31985',
			'1516257984-b1b4d707412e',
			'1489987707025-afc232f7ea0f',
			'1576995853123-5a10305d93c0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Kenzo Shibuya', review: 'Daiki Suzuki’s pattern drafting shines here. The sleeve articulation and pocket placements are workwear perfection.' },
			{ rating: 5, reviewerName: 'Miles Morales', review: 'Flight satin catches light with a subtle industrial sheen. Warm without feeling cumbersome.' },
			{ rating: 4, reviewerName: 'Julian Alvarez', review: 'Collector piece quality. Heavyweight wool-blend ribbed collar sits clean against collared shirts.' },
		],
	},
	{
		name: 'Veja Campo White Leather ChromeFree Sneakers',
		brand: 'Veja',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'athletic-footwear',
		description: 'Sustainable minimalist street sneaker made from ChromeFree bovine leather with wild Amazonian rubber soles and recycled organic cotton lining.',
		variantName: 'White Black Logo',
		weight: 0.82,
		sizes: [
			{ size: 'EU 40', price: 175, discount: 0, quantity: 15 },
			{ size: 'EU 41', price: 175, discount: 0, quantity: 24 },
			{ size: 'EU 42', price: 175, discount: 0, quantity: 28 },
			{ size: 'EU 43', price: 175, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Leather', value: '100% ChromeFree Bovine Leather' },
			{ name: 'Sole Compound', value: 'Amazonian wild rubber, rice waste, and recycled rubber' },
			{ name: 'Lining', value: 'Tech 100% recycled polyester jersey' },
		],
		photoIds: [
			'1549298916-b41d501d3772',
			'1560769629-975ec94e6a86',
			'1595950653106-6c9ebd614d3a',
			'1542291026-7eec264c27ff',
			'1608256246200-53e635b5b65f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Camille Dupont', review: 'Eco-conscious craftsmanship without sacrificing clean contemporary aesthetic. Extremely easy to style.' },
			{ rating: 5, reviewerName: 'Daniel Vance', review: 'Chunky sole provides good arch cushion for long walking tours across cobblestones.' },
			{ rating: 4, reviewerName: 'Mia Wallace', review: 'Leather is substantial at first and breaks in to a pliable softness within 3 to 4 wears.' },
		],
	},
	{
		name: 'Carhartt WIP Detroit Heavy Duck Canvas Jacket',
		brand: 'Carhartt WIP',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-outerwear',
		description: 'Rugged street heritage icon made from 12oz organic Dearborn canvas with corduroy top collar, blanket lining, and signature gold-tone chest zip.',
		variantName: 'Hamilton Brown',
		weight: 1.35,
		sizes: [
			{ size: 'Small', price: 235, discount: 0, quantity: 14 },
			{ size: 'Medium', price: 235, discount: 0, quantity: 25 },
			{ size: 'Large', price: 235, discount: 0, quantity: 22 },
			{ size: 'X-Large', price: 235, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Canvas', value: '100% Organic Cotton 12oz Dearborn Canvas' },
			{ name: 'Body Lining', value: 'Striped Blanket Lining / Nylon Sleeve Lining' },
			{ name: 'Details', value: 'Corduroy top collar, zippered chest pocket, snap-adjustable cuffs' },
		],
		photoIds: [
			'1551028719-00167b16eac5',
			'1544441893-675973e31985',
			'1516257984-b1b4d707412e',
			'1489987707025-afc232f7ea0f',
			'1576995853123-5a10305d93c0',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Zack Morris', review: 'The blanket lining provides just the right amount of core insulation against autumn chills.' },
			{ rating: 5, reviewerName: 'Brandon Walsh', review: 'Dearborn canvas is stiff when brand new, but after a season it conforms to your posture like armor.' },
			{ rating: 4, reviewerName: 'Toby Flenderson', review: 'Classic boxy workwear cut with snap tabs at waist to taper the hem if desired.' },
		],
	},
	{
		name: 'Outlier Slim Dungarees Technical Trousers',
		brand: 'Outlier',
		categoryUrl: 'fashion-apparel',
		subCategoryUrl: 'mens-clothing',
		description: 'The definitive 21st-century travel pant crafted in Switzerland from workcloth doubleweave nylon with nano-pel DWR stain and rain resistance.',
		variantName: 'Charcoal Shadow',
		weight: 0.44,
		sizes: [
			{ size: '30 Waist', price: 198, discount: 0, quantity: 15 },
			{ size: '32 Waist', price: 198, discount: 0, quantity: 30 },
			{ size: '34 Waist', price: 198, discount: 0, quantity: 26 },
		],
		specs: [
			{ name: 'Fabric', value: 'F.Cloth 200gsm Doubleweave Nylon with Cordura grade durability' },
			{ name: 'Treatment', value: 'Fluorocarbon-free DWR moisture repellant' },
			{ name: 'Hardware', value: 'Custom Italian matte black shank button and YKK zipper' },
		],
		photoIds: [
			'1541099649105-f69ad21f3246',
			'1542272604-787c3835535d',
			'1582552938357-32b906dfca0f',
			'1576995853123-5a10305d93c0',
			'1489987707025-afc232f7ea0f',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Julian Assange-Cole', review: 'Coffee spills bead right off the nano-pel finish. Breathable in 30°C heat yet windproof down to 5°C.' },
			{ rating: 5, reviewerName: 'Peter Gregory', review: 'Two-way stretch makes long intercontinental flights feel like wearing lounge pants while looking tailored.' },
			{ rating: 4, reviewerName: 'Anton Chigurh', review: 'Deep fifth pocket holds modern smartphones vertically without poking your hip when bending.' },
		],
	},

	// ── HOME & LIVING (16 Products) ───────────────────────────────────────────
	{
		name: 'Breville Barista Touch Impress Espresso Machine',
		brand: 'Breville',
		categoryUrl: 'home-living',
		subCategoryUrl: 'espresso-machines',
		description: 'Assisted manual espresso machine with touchscreen swipe display, intelligent dosing, precision 10kg assisted tamping, and automatic microfoam milk steaming.',
		variantName: 'Brushed Stainless Steel',
		weight: 10.3,
		sizes: [
			{ size: 'Complete Barista Unit', price: 1499, discount: 0, quantity: 15 },
		],
		specs: [
			{ name: 'Heating System', value: 'ThermoJet with 3-second rapid heat up' },
			{ name: 'Grinder', value: 'Baratza European Precision Burrs with 30 settings' },
			{ name: 'Tamping', value: 'Impression Puck System with 7-degree barista twist' },
		],
		photoIds: [
			'1514432324607-a09d9b4aefdd',
			'1517668808822-9ebb02ae2a0e',
			'1509785307050-d4066910ec1e',
			'1517256064527-09c73fc73e38',
			'1495474472287-4d71bcdd2085',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Marco Bellini', review: 'The assisted tamping system solves inconsistent channeling completely. Extracts rich hazelnut crema every single morning.' },
			{ rating: 5, reviewerName: 'Jennifer Aniston-Lee', review: 'Auto MilQ creates glossy microfoam texture that pours clean latte art rosettas with zero guesswork.' },
			{ rating: 4, reviewerName: 'Timothy Keller', review: 'The touchscreen walk-through guides you through dialing in new roast profiles seamlessly.' },
		],
	},
	{
		name: 'Le Creuset Signature Enameled Cast Iron Dutch Oven',
		brand: 'Le Creuset',
		categoryUrl: 'home-living',
		subCategoryUrl: 'kitchen-dining',
		description: 'The gold standard French culinary heirloom crafted in Fresnoy-le-Grand from enameled cast iron for superior heat distribution and retention.',
		variantName: 'Cerise Cherry Red',
		weight: 5.1,
		sizes: [
			{ size: '5.5 Quart Round', price: 420, discount: 0, quantity: 20 },
			{ size: '7.25 Quart Round', price: 460, discount: 0, quantity: 14 },
		],
		specs: [
			{ name: 'Material', value: 'Vitrified Enameled Cast Iron' },
			{ name: 'Knob', value: 'Stainless steel knob safe up to 500°F (260°C)' },
			{ name: 'Origin', value: 'Crafted in France since 1925' },
		],
		photoIds: [
			'1584269600464-37b1b58a9fe7',
			'1556911220-e15b29be8c8f',
			'1544233726-9f1d2b27be8b',
			'1556912172-45b7abe8b7e1',
			'1583394293214-28ded15ee548',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Julia Child-Vance', review: 'Browning meats creates incredible fond without burning, and sourdough boules bake with crackling golden crusts.' },
			{ rating: 5, reviewerName: 'Thomas Keller-Ross', review: 'The sand-colored interior enamel makes it easy to monitor caramelization progress. Cleans effortlessly with warm soap and water.' },
			{ rating: 4, reviewerName: 'Gordon Ramsay-Cole', review: 'Heavy, tight-fitting lid circulates steam moisture back onto roasts throughout low-and-slow braising.' },
		],
	},
	{
		name: 'Fellow Stagg EKG Electric Pour-Over Kettle',
		brand: 'Fellow',
		categoryUrl: 'home-living',
		subCategoryUrl: 'espresso-machines',
		description: 'Precision variable temperature pour-over kettle with fluted gooseneck spout, high-res LCD screen, and 60-minute temperature hold.',
		variantName: 'Matte Black with Walnut Handle',
		weight: 1.25,
		sizes: [
			{ size: '0.9 Liter Studio', price: 195, discount: 0, quantity: 30 },
		],
		specs: [
			{ name: 'Power', value: '1200W Rapid Heating Element' },
			{ name: 'Temperature Range', value: '135°F to 212°F (57°C to 100°C) to the exact degree' },
			{ name: 'Spout', value: 'Counterbalanced fluted gooseneck for laminar flow control' },
		],
		photoIds: [
			'1514432324607-a09d9b4aefdd',
			'1509785307050-d4066910ec1e',
			'1517668808822-9ebb02ae2a0e',
			'1495474472287-4d71bcdd2085',
			'1517256064527-09c73fc73e38',
		],
		reviews: [
			{ rating: 5, reviewerName: 'James Hoffmann-Smith', review: 'The counterbalanced handle and gooseneck tip give pinpoint flow rate control when blooming delicate Geisha roasts.' },
			{ rating: 5, reviewerName: 'Sarah Lin', review: 'Holds target temperature for a full hour. The built-in brew stopwatch timer is a delightful touch.' },
			{ rating: 4, reviewerName: 'Kyle Larson', review: 'Sculptural matte silhouette looks like modern art sitting on the kitchen countertop.' },
		],
	},
	{
		name: 'Herman Miller Aeron Ergonomic Chair Remastered',
		brand: 'Herman Miller',
		categoryUrl: 'home-living',
		subCategoryUrl: 'living-room-seating',
		description: 'The world benchmark in ergonomic task seating engineered with Pellicle 8Z elastomeric suspension, PostureFit SL sacral support, and harmonic tilt.',
		variantName: 'Graphite Frame',
		weight: 18.5,
		sizes: [
			{ size: 'Size B (Medium)', price: 1495, discount: 0, quantity: 18 },
			{ size: 'Size C (Large)', price: 1495, discount: 0, quantity: 12 },
		],
		specs: [
			{ name: 'Suspension', value: 'Pellicle 8Z breathable elastomeric mesh' },
			{ name: 'Support', value: 'Dual adjustable PostureFit SL pads' },
			{ name: 'Warranty', value: '12-Year 24/7 Multi-Shift Manufacturer Warranty' },
		],
		photoIds: [
			'1580481077195-731da03fed1e',
			'1567538096630-e0c55bd6374c',
			'1555041469-a586c61ea9bc',
			'1586023492125-27b2c045efd7',
			'1507473885765-e6ed057f782c',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dr. Gregory House', review: 'Eliminated lower back tightness completely within three days of switching from a standard foam executive chair.' },
			{ rating: 5, reviewerName: 'Wozniak Steve', review: 'The breathable mesh keeps you cool through 10-hour software development marathons. Forward tilt helps focus.' },
			{ rating: 4, reviewerName: 'Dan Harmon', review: 'Harmonic tilt mechanism pivots smoothly from active typing posture to relaxed reclining.' },
		],
	},
	{
		name: 'Chemex 8-Cup Classic Pour-Over Glass Coffeemaker',
		brand: 'Chemex',
		categoryUrl: 'home-living',
		subCategoryUrl: 'espresso-machines',
		description: 'Museum of Modern Art permanent collection pour-over carafe made from non-porous borosilicate glass with polished wood collar and leather tie.',
		variantName: 'Clear Glass with Wood Collar',
		weight: 0.75,
		sizes: [
			{ size: '8-Cup (40 oz)', price: 49, discount: 0, quantity: 45 },
		],
		specs: [
			{ name: 'Material', value: 'High-purity laboratory grade Borosilicate Glass' },
			{ name: 'Collar', value: 'Polished genuine hardwood with rawhide leather lace' },
			{ name: 'Capacity', value: '40 Ounces / 1180 mL' },
		],
		photoIds: [
			'1514432324607-a09d9b4aefdd',
			'1509785307050-d4066910ec1e',
			'1517668808822-9ebb02ae2a0e',
			'1495474472287-4d71bcdd2085',
			'1517256064527-09c73fc73e38',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Clara Oswald', review: 'When paired with bonded Chemex filters, it brews the cleanest, most tea-like clarity cup of coffee imaginable.' },
			{ rating: 5, reviewerName: 'Benjamin Franklin-Lee', review: 'No mechanical parts to break. Elegant glass vessel serves as a centerpiece on the breakfast table.' },
			{ rating: 4, reviewerName: 'Lucas Grey', review: 'Simple, pure, and produces zero chemical bitterness or sediment.' },
		],
	},
	{
		name: 'Dyson Purifier Hot+Cool Formaldehyde Air Purifier',
		brand: 'Dyson',
		categoryUrl: 'home-living',
		subCategoryUrl: 'furniture-decor',
		description: 'Flagship whole-room air purifier, space heater, and cooling fan featuring solid-state formaldehyde sensor and fully sealed HEPA H13 filtration.',
		variantName: 'Nickel & Gold',
		weight: 5.7,
		sizes: [
			{ size: 'HP09 Whole-Room Unit', price: 749, discount: 5, quantity: 15 },
		],
		specs: [
			{ name: 'Filtration', value: 'HEPA H13 captures 99.97% of particles down to 0.3 microns' },
			{ name: 'Sensors', value: 'Continuous acoustic formaldehyde, VOC, PM2.5, PM10' },
			{ name: 'Heating', value: 'PTC ceramic plates with thermostatic room control' },
		],
		photoIds: [
			'1580481077195-731da03fed1e',
			'1555041469-a586c61ea9bc',
			'1586023492125-27b2c045efd7',
			'1567538096630-e0c55bd6374c',
			'1507473885765-e6ed057f782c',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Dr. Allison Cameron', review: 'Automatically ramps fan speed up when cooking bacon in the kitchen. Noticed dramatic reduction in morning allergic congestion.' },
			{ rating: 5, reviewerName: 'Richard Hendricks', review: 'The quiet night mode dims the LCD screen and runs silently below 35dB. The MyDyson app analytics are detailed.' },
			{ rating: 4, reviewerName: 'Erlich Bachman', review: 'Heats our master bedroom rapidly during freezing winter mornings without burnt dust smells.' },
		],
	},
	{
		name: 'Balmuda The Toaster Steam Convection Oven',
		brand: 'Balmuda',
		categoryUrl: 'home-living',
		subCategoryUrl: 'kitchen-dining',
		description: 'Japanese culinary innovation that uses 5cc of steam and precise micro-temperature regulation to revive bakery-fresh artisan bread with crisp crusts.',
		variantName: 'Matte Charcoal Black',
		weight: 4.3,
		sizes: [
			{ size: 'Standard Countertop Unit', price: 299, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Steam Tech', value: '5cc water steam chamber envelope' },
			{ name: 'Heating Modes', value: 'Sandwich, Artisan Bread, Pizza, Croissant, Classic 450°F' },
			{ name: 'Timer', value: '1 to 15 minute acoustic analog mechanical dial' },
		],
		photoIds: [
			'1556911220-e15b29be8c8f',
			'1584269600464-37b1b58a9fe7',
			'1544233726-9f1d2b27be8b',
			'1556912172-45b7abe8b7e1',
			'1583394293214-28ded15ee548',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Chef Kenji Lopez', review: 'Reheats day-old croissants into flaky, buttery perfection with molten interior texture that beats regular ovens completely.' },
			{ rating: 5, reviewerName: 'Yuki Takahashi', review: 'The steam seals in moisture before radiant heat crisps the surface. Sourdough toast is crunchy on outside, pillow soft inside.' },
			{ rating: 4, reviewerName: 'Claire Saffitz-Vance', review: 'Charming chime sounds when the timer completes. Compact footprint fits seamlessly on small apartment counters.' },
		],
	},
	{
		name: 'Vitamix A3500 Ascent Series Smart Blender',
		brand: 'Vitamix',
		categoryUrl: 'home-living',
		subCategoryUrl: 'kitchen-dining',
		description: 'Commercial-grade power blender featuring 5 program settings, touchscreen controls, programmable timer, and Self-Detect container technology.',
		variantName: 'Brushed Stainless Metal',
		weight: 6.8,
		sizes: [
			{ size: '64 oz Low-Profile Container', price: 649, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Motor', value: '2.2 peak horsepower commercial motor' },
			{ name: 'Blades', value: 'Laser-cut hardened stainless steel hammer blades' },
			{ name: 'Presets', value: 'Smoothies, Hot Soups, Dips & Spreads, Frozen Desserts, Self-Cleaning' },
		],
		photoIds: [
			'1556911220-e15b29be8c8f',
			'1584269600464-37b1b58a9fe7',
			'1544233726-9f1d2b27be8b',
			'1556912172-45b7abe8b7e1',
			'1583394293214-28ded15ee548',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Mark Bittman', review: 'Pours raw cold vegetables and broth in, runs soup cycle, and 5 minutes later serves steaming hot pureed butternut squash soup.' },
			{ rating: 5, reviewerName: 'Jessica Seinfeld', review: 'Crushes whole frozen fruits, nut butters, and fibrous kale into completely silken smoothies with zero grit.' },
			{ rating: 4, reviewerName: 'Alton Brown', review: 'Low-profile container fits under standard upper kitchen cabinets. Built to last 20+ years.' },
		],
	},
	{
		name: 'Staub Cast Iron 4-Quart Round Cocotte',
		brand: 'Staub',
		categoryUrl: 'home-living',
		subCategoryUrl: 'kitchen-dining',
		description: 'French culinary masterpiece featuring textured matte black enamel interior for superior searing, and patented Chistera drop-structure self-basting lid.',
		variantName: 'Dark Grenadine Majolica',
		weight: 4.8,
		sizes: [
			{ size: '4-Quart Round', price: 319, discount: 10, quantity: 22 },
		],
		specs: [
			{ name: 'Enamel', value: 'Multi-layer glass vitreous majolica enamel' },
			{ name: 'Lid System', value: 'Spike drop structure rain-forest continuous basting' },
			{ name: 'Heat Resistance', value: 'Oven safe up to 900°F without lid / 500°F with lid' },
		],
		photoIds: [
			'1584269600464-37b1b58a9fe7',
			'1556911220-e15b29be8c8f',
			'1544233726-9f1d2b27be8b',
			'1556912172-45b7abe8b7e1',
			'1583394293214-28ded15ee548',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Chef Ludo Lefebvre', review: 'The matte black interior achieves a deeper sear and crust on short ribs than slick cream enamel pots.' },
			{ rating: 5, reviewerName: 'Gail Simmons', review: 'The spiked underside of the heavy lid continuously rains condensation across braising stews.' },
			{ rating: 4, reviewerName: 'Eric Ripert-Vance', review: 'Deep grenadine glaze has gorgeous jewel-like color depth when placed directly onto the dinner table.' },
		],
	},
	{
		name: 'Anglepoise Original 1227 Balanced Desk Lamp',
		brand: 'Anglepoise',
		categoryUrl: 'home-living',
		subCategoryUrl: 'furniture-decor',
		description: 'The archetype spring-balanced task lamp designed by George Carwardine in 1935 with heritage cast iron base, chrome arms, and embossed aluminum shade.',
		variantName: 'Linen White Gloss',
		weight: 3.6,
		sizes: [
			{ size: 'Standard Desk Lamp', price: 295, discount: 0, quantity: 25 },
		],
		specs: [
			{ name: 'Mechanism', value: 'Patented constant-tension 3-spring balanced articulation' },
			{ name: 'Base', value: 'Cast iron with pressed steel cover' },
			{ name: 'Reach', value: 'Maximum horizontal reach of 60cm' },
		],
		photoIds: [
			'1507473885765-e6ed057f782c',
			'1580481077195-731da03fed1e',
			'1567538096630-e0c55bd6374c',
			'1555041469-a586c61ea9bc',
			'1586023492125-27b2c045efd7',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Sir Kenneth Grange', review: 'Positions exactly where directed with a light fingertip touch and stays anchored without drooping.' },
			{ rating: 5, reviewerName: 'Fiona Gallagher', review: 'Cast iron base is reassuringly heavy. Provides clean directional task light for drafting and evening book reading.' },
			{ rating: 4, reviewerName: 'Tom Dixon-Smith', review: 'Timeless industrial British design that harmonizes with both vintage oak and modern glass desks.' },
		],
	},
	{
		name: 'HAY Neu 13 Ergonomic Solid Oak Dining Chair',
		brand: 'HAY',
		categoryUrl: 'home-living',
		subCategoryUrl: 'dining-furniture',
		description: 'Danish modern dining chair with organically curved ergonomic polypropylene shell and solid lacquered oak legs designed for long dinner conversations.',
		variantName: 'Warm White Shell / Natural Oak',
		weight: 5.4,
		sizes: [
			{ size: 'Single Chair', price: 295, discount: 0, quantity: 30 },
			{ size: 'Set of 4 Chairs', price: 1080, discount: 8, quantity: 10 },
		],
		specs: [
			{ name: 'Shell Material', value: 'Injection-molded solid-dyed polypropylene' },
			{ name: 'Base Legs', value: 'Solid FSC-Certified European Oak' },
			{ name: 'Seat Height', value: '46 cm (Standard Dining Height)' },
		],
		photoIds: [
			'1580481077195-731da03fed1e',
			'1567538096630-e0c55bd6374c',
			'1555041469-a586c61ea9bc',
			'1586023492125-27b2c045efd7',
			'1507473885765-e6ed057f782c',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Mette Hay', review: 'Subtle rim detail along the curved backrest provides supportive lumbar posture through multi-course dinners.' },
			{ rating: 5, reviewerName: 'Henrik Pedersen', review: 'Oak joinery is robust and solid. Polypropylene seat wipes clean instantly after family meals.' },
			{ rating: 4, reviewerName: 'Cecilie Manz', review: 'Minimalist Danish proportions tuck neatly under round and rectangular dining tables alike.' },
		],
	},
	{
		name: 'Moccamaster KBGV Select 10-Cup Coffee Maker',
		brand: 'Technivorm',
		categoryUrl: 'home-living',
		subCategoryUrl: 'espresso-machines',
		description: 'Handmade in the Netherlands batch brewer certified by the Specialty Coffee Association for precise 196°F–205°F water extraction and hot-plate regulation.',
		variantName: 'Brushed Silver',
		weight: 2.8,
		sizes: [
			{ size: '10-Cup Glass Carafe', price: 349, discount: 0, quantity: 24 },
		],
		specs: [
			{ name: 'Brew Temperature', value: 'Copper boiling element regulates 196°F–205°F' },
			{ name: 'Brew Time', value: 'Full 1.25L carafe in 4 to 6 minutes' },
			{ name: 'Selector Switch', value: 'Half-carafe or full-carafe flow rate optimization' },
		],
		photoIds: [
			'1514432324607-a09d9b4aefdd',
			'1509785307050-d4066910ec1e',
			'1517668808822-9ebb02ae2a0e',
			'1495474472287-4d71bcdd2085',
			'1517256064527-09c73fc73e38',
		],
		reviews: [
			{ rating: 5, reviewerName: 'SCA Inspector #44', review: 'Consistent brew temperature from first second of water delivery through end of brew cycle. Extracts rich sweetness.' },
			{ rating: 5, reviewerName: 'Annika Sorenstam', review: 'Industrial copper heating element ensures morning coffee is piping hot. Simple manual toggle switch reliability.' },
			{ rating: 4, reviewerName: 'Nate Silver-Smith', review: 'Modular pieces are dishwasher safe and easy to clean. Classic Dutch mid-century silhouette.' },
		],
	},
	{
		name: 'Parachute Brushed Cotton Sheet Set',
		brand: 'Parachute',
		categoryUrl: 'home-living',
		subCategoryUrl: 'linen-bedding',
		description: 'Buttery soft bedding crafted in Portugal from 100% certified long-staple cotton brushed for a lived-in, flannel-like softness without excess heat.',
		variantName: 'Bone Ivory',
		weight: 2.4,
		sizes: [
			{ size: 'Queen Sheet Set', price: 169, discount: 0, quantity: 25 },
			{ size: 'King Sheet Set', price: 189, discount: 0, quantity: 20 },
		],
		specs: [
			{ name: 'Material', value: '100% Long-Staple Cotton, Brushed Finish' },
			{ name: 'Certification', value: 'OEKO-TEX Standard 100 Certified' },
			{ name: 'Set Includes', value: '1 Fitted Sheet, 1 Flat Sheet, 2 Pillowcases' },
		],
		photoIds: [
			'1580481077195-731da03fed1e',
			'1586023492125-27b2c045efd7',
			'1555041469-a586c61ea9bc',
			'1567538096630-e0c55bd6374c',
			'1507473885765-e6ed057f782c',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Brooke Shields-Vance', review: 'Feels like your favorite broken-in vintage t-shirt from the very first night. Breathable and cozy.' },
			{ rating: 5, reviewerName: 'Carter Reum', review: 'Fitted sheet has deep 16-inch elastic corners that never pop off our high-profile hybrid mattress.' },
			{ rating: 4, reviewerName: 'Gretchen Rossi', review: 'Washes beautifully without stiffening or wrinkling into tight balls. Subtle matte luxury.' },
		],
	},
	{
		name: 'Aarke Carbonator Pro Glass Bottle Sparkling Water Maker',
		brand: 'Aarke',
		categoryUrl: 'home-living',
		subCategoryUrl: 'kitchen-dining',
		description: 'Architectural Swedish sparkling water machine crafted from seamless stainless steel with motorized cover and dishwasher-safe glass bottle.',
		variantName: 'Matte Sand Finish',
		weight: 3.65,
		sizes: [
			{ size: 'Carbonator Pro Unit + Glass Bottle', price: 349, discount: 0, quantity: 18 },
		],
		specs: [
			{ name: 'Chassis', value: 'Seamless precision stainless steel unibody' },
			{ name: 'Bottle', value: 'Dishwasher-safe 800ml Glass Carafe with stainless cap' },
			{ name: 'Mechanism', value: 'Push2Clean single-handed internal pushdown chamber' },
		],
		photoIds: [
			'1556911220-e15b29be8c8f',
			'1584269600464-37b1b58a9fe7',
			'1544233726-9f1d2b27be8b',
			'1556912172-45b7abe8b7e1',
			'1583394293214-28ded15ee548',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Jonas Groth', review: 'Operates with smooth mechanical precision. Eliminates thousands of single-use plastic club soda bottles every year.' },
			{ rating: 5, reviewerName: 'Carl Ljungberg', review: 'The glass bottle feels refined at the dinner table. Carbonation levels are crisp and effervescent.' },
			{ rating: 4, reviewerName: 'Astrid Lindgren-Smith', review: 'Completely cordless design allows placement on bar carts or kitchen islands with no unsightly cords.' },
		],
	},
	{
		name: 'Muuto Linear Steel Outdoor Dining Table',
		brand: 'Muuto',
		categoryUrl: 'home-living',
		subCategoryUrl: 'dining-furniture',
		description: 'Contemporary Scandinavian outdoor table by Thomas Bentzen designed with straight lines, folded edges, and weather-resistant matte powder-coated steel.',
		variantName: 'Dark Green Matte',
		weight: 29.0,
		sizes: [
			{ size: '140 x 80 cm', price: 1295, discount: 0, quantity: 8 },
			{ size: '200 x 80 cm', price: 1695, discount: 0, quantity: 6 },
		],
		specs: [
			{ name: 'Steel Coating', value: 'Hot-dip galvanized, aluzinc, and outdoor powder coat' },
			{ name: 'Water Drainage', value: 'Subtle folded center gap allows rainwater run-off' },
			{ name: 'Origin', value: 'Manufactured in Sweden' },
		],
		photoIds: [
			'1580481077195-731da03fed1e',
			'1567538096630-e0c55bd6374c',
			'1555041469-a586c61ea9bc',
			'1586023492125-27b2c045efd7',
			'1507473885765-e6ed057f782c',
		],
		reviews: [
			{ rating: 5, reviewerName: 'Thomas Bentzen', review: 'Folded edges soften the industrial steel sheet lines. The center slot ensures rainwater drains away immediately.' },
			{ rating: 5, reviewerName: 'Ingrid Bergman-Cole', review: 'Zero rust or finish degradation after an entire rainy coastal winter on our uncovered patio.' },
			{ rating: 4, reviewerName: 'Soren Kierkegaard-Ross', review: 'Heavy enough to withstand high coastal winds without shifting across stone pavers.' },
		],
	},
	{
		name: 'Nespresso Vertuo Creatista Machine by Breville',
		brand: 'Nespresso',
		categoryUrl: 'home-living',
		subCategoryUrl: 'espresso-machines',
		description: 'High-end single-serve espresso and coffee maker featuring integrated Auto MilQ steam wand with 8 texture levels and 11 milk temperature settings.',
		variantName: 'Stainless Steel',
		weight: 6.9,
		sizes: [
			{ size: 'Creatista Machine Unit', price: 749, discount: 0, quantity: 14 },
		],
		specs: [
			{ name: 'Extraction', value: 'Centrifusion technology up to 4000 RPM' },
			{ name: 'Steam Wand', value: 'Automated ThermoJet steam wand with auto-purge' },
			{ name: 'Capsule Compatibility', value: 'Vertuo capsules from 1.35oz espresso to 18oz carafe' },
		],
		photoIds: [
			'1514432324607-a09d9b4aefdd',
			'1509785307050-d4066910ec1e',
			'1517668808822-9ebb02ae2a0e',
			'1495474472287-4d71bcdd2085',
			'1517256064527-09c73fc73e38',
		],
		reviews: [
			{ rating: 5, reviewerName: 'George Clooney-Vance', review: 'Brings authentic commercial cafe steam wand performance to the speed and convenience of single-touch capsules.' },
			{ rating: 5, reviewerName: 'Penelope Cruz', review: 'The auto-purge steam cycle cleans the wand tip after every drink so milk never burns on.' },
			{ rating: 4, reviewerName: 'Hugh Grant-Smith', review: 'Substantial brushed metal casing looks refined alongside professional grinders.' },
		],
	},
];
