import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AnalyticsDateRange } from '@/components/dashboard/admin/analytics-date-range';
import { MarketplaceStatusBadge } from '@/components/dashboard/admin/marketplace-status-badge';
import { MetricCard } from '@/components/dashboard/admin/metric-card';
import StoreStatusSelect from '@/components/dashboard/forms/store-status-select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { UrlPagination } from '@/components/ui/url-pagination';
import { getAdminStoreProfile } from '@/queries/admin-store-operations';
import { StoreStatus } from '@/lib/types';

function usd(cents: number) {
	return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
}

function date(value: Date | null | undefined) {
	return value ? value.toLocaleDateString('en-US', { timeZone: 'UTC' }) : '—';
}

function payoutReadiness(account: { status: string; transfersCapability: string | null; detailsSubmitted: boolean } | null) {
	if (!account) return 'NOT CONNECTED';
	if (account.status === 'ACTIVE' && account.transfersCapability === 'ACTIVE' && account.detailsSubmitted) return 'READY';
	if (account.status === 'ACTIVE') return 'REVIEW REQUIRED';
	return account.status;
}

export default async function AdminStoreProfilePage({
	params,
	searchParams,
}: {
	params: Promise<{ storeId: string }>;
	searchParams: Promise<{ ledgerPage?: string; from?: string; to?: string }>;
}) {
	const [{ storeId }, query] = await Promise.all([params, searchParams]);
	const profile = await getAdminStoreProfile(storeId, query);
	if (!profile) notFound();
	const { store, performance, financials } = profile;
	const rangeLabel = profile.dateRange.from || profile.dateRange.to ? `${profile.dateRange.from ?? 'Beginning'} – ${profile.dateRange.to ?? 'Today'}` : 'All time';

	return <div className='w-full max-w-none space-y-6 pb-12'>
		<header className='flex flex-wrap items-start justify-between gap-4 border-b border-border/60 pb-5'>
			<div><div className='mb-2 flex items-center gap-2 text-sm text-muted-foreground'><Link href='/dashboard/admin/stores' className='hover:text-foreground'>Stores</Link><span>/</span><span>Store operations</span></div><h1 className='text-2xl font-bold tracking-tight'>{store.name}</h1><p className='mt-1 text-sm text-muted-foreground'>/{store.url} · Created {date(store.createdAt)} · All monetary values are USD.</p></div>
			<div className='flex flex-wrap items-center gap-2'><StoreStatusSelect storeId={store.id} status={store.status as StoreStatus} /><Link href={`/store/${store.url}`} className='rounded-lg border border-border px-3 py-2 text-sm font-medium transition-colors hover:bg-muted'>Open storefront</Link></div>
		</header>

		<section className='grid gap-4 lg:grid-cols-2'>
			<Card className='gap-0 py-0 shadow-none'><CardHeader><CardTitle>Accountable seller</CardTitle></CardHeader><CardContent className='grid gap-3 pb-5 text-sm sm:grid-cols-2'><div><p className='text-muted-foreground'>Seller</p><Link href={`/dashboard/admin/sellers/${store.user.id}`} className='mt-1 block font-semibold hover:text-primary'>{store.user.name}</Link><p className='text-xs text-muted-foreground'>{store.user.email}</p></div><div><p className='text-muted-foreground'>Payout readiness</p><div className='mt-1'><MarketplaceStatusBadge status={payoutReadiness(store.user.paymentAccount)} /></div><p className='mt-1 text-xs text-muted-foreground'>{store.user.paymentAccount?.requirementsDueCount ?? 0} requirements due · transfers {store.user.paymentAccount?.transfersCapability?.toLowerCase() ?? 'not connected'} · no bank or KYC data shown</p></div></CardContent></Card>
			<Card className='gap-0 py-0 shadow-none'><CardHeader><CardTitle>Store operations</CardTitle></CardHeader><CardContent className='grid gap-3 pb-5 text-sm sm:grid-cols-2'><div><p className='text-muted-foreground'>Delivery</p><p className='mt-1 font-medium'>{store.defaultShippingService}</p><p className='text-xs text-muted-foreground'>{store.defaultDeliveryTimeMin}–{store.defaultDeliveryTimeMax} days</p></div><div><p className='text-muted-foreground'>Returns</p><p className='mt-1 font-medium'>{store.returnsAccepted ? 'Accepted' : 'Not accepted'}</p><p className='text-xs text-muted-foreground'>{store.returnsAccepted ? `${store.returnWindowDays}-day window${store.returnShippingFees ? ' · seller pays return shipping' : ''}` : 'No return window'}</p></div><div><p className='text-muted-foreground'>Audience</p><p className='mt-1 font-medium'>{store._count.followers} followers</p><p className='text-xs text-muted-foreground'>{store._count.coupons} coupons · {store._count.returnRequests} return requests</p></div><div><p className='text-muted-foreground'>Merchandising</p><p className='mt-1 font-medium'>{store.featured ? 'Featured store' : 'Standard placement'}</p><p className='text-xs text-muted-foreground'>{store._count.products} products · {store._count.orderGroups} order groups</p></div></CardContent></Card>
		</section>

		<section className='rounded-xl border border-border p-5'><div className='flex flex-wrap items-end justify-between gap-4'><div><h2 className='text-lg font-semibold'>Performance</h2><p className='mt-1 text-sm text-muted-foreground'>Paid orders only · {rangeLabel}. Use a date range to inspect a campaign or operating period.</p></div><form method='get'><AnalyticsDateRange from={query.from} to={query.to} prefix='store-performance' /></form></div>{!profile.dateRange.valid && <p role='alert' className='mt-3 rounded-md border border-red-300 bg-red-50 p-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-950/40 dark:text-red-300'>Choose valid dates where the From date is on or before the To date.</p>}<div className='mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5'><MetricCard label='Paid sales' value={usd(performance.netSalesCents)} supporting={`${performance.paidOrders} paid orders`} /><MetricCard label='Units sold' value={performance.unitsSold} supporting={`${usd(performance.averageOrderValueCents)} average order`} /><MetricCard label='Customer rating' value={`${performance.averageRating.toFixed(1)} / 5`} supporting={`${performance.reviewCount} reviews in range`} /><MetricCard label='Catalog' value={store._count.products} supporting={`${store._count.orderGroups} total order groups`} /><MetricCard label='Store rating' value={`${store.averageRating.toFixed(1)} / 5`} supporting={`${store.numReviews} lifetime reviews`} /></div></section>

		<section className='rounded-xl border border-border p-5'><div><h2 className='text-lg font-semibold'>Store financial statement</h2><p className='mt-1 text-sm text-muted-foreground'>Immutable settlement facts across this store. GoCart commission is recorded marketplace revenue; operating cost data is not modeled, so it is not labelled profit.</p></div><div className='mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6'><MetricCard label='Gross sales' value={usd(financials.grossCents)} /><MetricCard label='Discounts' value={usd(financials.discountCents)} /><MetricCard label='GoCart commission' value={usd(financials.commissionCents)} /><MetricCard label='Refunds / reversals' value={usd(financials.refundedCents + financials.reversedCents)} /><MetricCard label='Outstanding seller balance' value={usd(financials.outstandingCents)} /><MetricCard label='Released to seller' value={usd(financials.releasedCents)} /></div>
			<div className='mt-6 rounded-lg border border-border'><Table className='min-w-[960px] text-left text-sm'><TableHeader className='bg-muted/50'><TableRow className='hover:bg-muted/50'><TableHead className='p-3'>Order group</TableHead><TableHead className='p-3'>Settlement</TableHead><TableHead className='p-3'>Gross</TableHead><TableHead className='p-3'>Commission</TableHead><TableHead className='p-3'>Seller payable</TableHead><TableHead className='p-3'>Ledger facts</TableHead></TableRow></TableHeader><TableBody>{profile.settlements.map((settlement) => <TableRow key={settlement.id} className='align-top border-border/60 transition-colors duration-150 hover:bg-accent/60 dark:hover:bg-accent/20'><TableCell className='p-3 font-mono text-xs'>{settlement.orderGroup.id.slice(0, 8)}<p className='mt-1 font-sans text-xs text-muted-foreground'>{date(settlement.orderGroup.createdAt)} · {settlement.orderGroup.packageStatus}</p></TableCell><TableCell className='p-3'><MarketplaceStatusBadge status={settlement.status} />{settlement.failureReason && <p className='mt-2 max-w-xs text-xs text-red-700 dark:text-red-300'>{settlement.failureReason}</p>}</TableCell><TableCell className='p-3'>{usd(settlement.grossCents)}</TableCell><TableCell className='p-3'>{usd(settlement.commissionCents)}</TableCell><TableCell className='p-3'>{usd(settlement.remainingPayableCents)}<p className='mt-1 text-xs text-muted-foreground'>of {usd(settlement.sellerPayableCents)}</p></TableCell><TableCell className='p-3 text-xs text-muted-foreground'>{settlement.entries.map((entry) => <p key={entry.id}>{entry.entryType}: {usd(entry.sellerPayableCents)}</p>)}</TableCell></TableRow>)}{profile.settlements.length === 0 && <TableRow className='hover:bg-transparent'><TableCell colSpan={6} className='p-8 text-center text-muted-foreground'>No settlement ledger entries exist for this store.</TableCell></TableRow>}</TableBody></Table><UrlPagination label='Store settlement ledger pages' param='ledgerPage' {...profile.settlementPagination} /></div></section>

		<section className='grid gap-6 xl:grid-cols-2'><Card className='gap-0 py-0 shadow-none'><CardHeader><CardTitle>Top products by paid revenue</CardTitle></CardHeader><CardContent className='pb-5'><div className='overflow-hidden rounded-lg border border-border'><Table className='min-w-[620px]'><TableHeader className='bg-muted/50'><TableRow className='hover:bg-muted/50'><TableHead className='p-3'>Product</TableHead><TableHead className='p-3'>Units</TableHead><TableHead className='p-3'>Revenue</TableHead></TableRow></TableHeader><TableBody>{performance.topProducts.map((product) => <TableRow key={`${product.productId}-${product.productSlug}`} className='transition-colors duration-150 hover:bg-accent/60 dark:hover:bg-accent/20'><TableCell className='p-3'><p className='font-medium'>{product.name}</p><p className='text-xs text-muted-foreground'>{product.productSlug}</p></TableCell><TableCell className='p-3'>{product.unitsSold}</TableCell><TableCell className='p-3'>{usd(product.revenueCents)}</TableCell></TableRow>)}{performance.topProducts.length === 0 && <TableRow className='hover:bg-transparent'><TableCell colSpan={3} className='p-8 text-center text-muted-foreground'>No paid product sales in this date range.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>
			<Card className='gap-0 py-0 shadow-none'><CardHeader><CardTitle>Recent paid order groups</CardTitle></CardHeader><CardContent className='pb-5'><div className='overflow-hidden rounded-lg border border-border'><Table className='min-w-[620px]'><TableHeader className='bg-muted/50'><TableRow className='hover:bg-muted/50'><TableHead className='p-3'>Order group</TableHead><TableHead className='p-3'>Fulfilment</TableHead><TableHead className='p-3'>Settlement</TableHead><TableHead className='p-3'>Total</TableHead></TableRow></TableHeader><TableBody>{performance.recentOrders.map((order) => <TableRow key={order.id} className='transition-colors duration-150 hover:bg-accent/60 dark:hover:bg-accent/20'><TableCell className='p-3 font-mono text-xs'>{order.id.slice(0, 8)}<p className='mt-1 font-sans text-xs text-muted-foreground'>{date(order.createdAt)}</p></TableCell><TableCell className='p-3'>{order.packageStatus}</TableCell><TableCell className='p-3'>{order.settlement ? <MarketplaceStatusBadge status={order.settlement.status} /> : <span className='text-sm text-muted-foreground'>Not created</span>}</TableCell><TableCell className='p-3'>{usd(Math.round(order.total * 100))}</TableCell></TableRow>)}{performance.recentOrders.length === 0 && <TableRow className='hover:bg-transparent'><TableCell colSpan={4} className='p-8 text-center text-muted-foreground'>No paid order groups in this date range.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card></section>
	</div>;
}
